// Copyright (c) Aura development team - Licensed under GNU GPL
// For more information, see license file in the main folder

using System.Collections.Generic;
using System.Reflection;

namespace PaleTree.Shared
{
	public static class Op
	{
		public const int CB_LOGIN = 0x03; // Size: 4477
		public const int CB_LOGIN_BY_PASSPORT = 0x04; // Size: 1174
		public const int CB_LOGOUT = 0x05; // Size: 22
		public const int CB_START_GAME = 0x0c; // Size: 25
		public const int CB_START_BARRACK = 0x06; // Size: 23
		public const int CB_COMMANDER_CREATE = 0x07; // Size: 113
		public const int CB_COMMANDER_DESTROY = 0x09; // Size: 30
		public const int CB_CHECK_CLIENT_INTEGRITY = 0x0a; // Size: 86
		public const int CB_CLIENT_INTEGRITY_FAIL = 0x0b; // Size: 1047
		public const int CB_NOT_AUTHORIZED_ADDON_LIST = 0x53; // Size: 1051
		public const int CB_ECHO = 0x10; // Size: 42
		public const int CB_BARRACKNAME_CHANGE = 0x0d; // Size: 86
		public const int CB_COMMANDER_MOVE = 0x0e; // Size: 43
		public const int CB_COMPANION_MOVE = 0x0f; // Size: 50
		public const int CB_CHECK_MARKET_REGISTERED = 0x57; // Size: 30
		public const int BC_LOGINOK = 0x11; // Size: 156
		public const int BC_CYOU_LOGIN_FAIL = 0x12; // Size: 16
		public const int BC_LOGIN_PACKET_RECEIVED = 0x13; // Size: 16
		public const int BC_LOGOUTOK = 0x14; // Size: 16
		public const int BC_START_GAMEOK = 0x18; // Size: 37
		public const int BC_SINGLE_INFO = 0x19; // Size: 385
		public const int BC_COMMANDER_LIST = 0x15; // Size: 0
		public const int BC_COMMANDER_CREATE_SLOTID = 0x08; // Size: 11
		public const int BC_COMMANDER_CREATE = 0x16; // Size: 530
		public const int BC_COMMANDER_DESTROY = 0x17; // Size: 11
		public const int BC_MESSAGE = 0x1a; // Size: 0
		public const int BC_ECHO = 0x1b; // Size: 30
		public const int BC_IES_MODIFY_INFO = 0x32; // Size: 0
		public const int BC_IES_MODIFY_LIST = 0x33; // Size: 0
		public const int CB_IES_REVISION_DELETE = 0x34; // Size: 0
		public const int BC_IES_REVISION_DELETE = 0x35; // Size: 0
		public const int BC_MYPAGE_MAP = 0x1c; // Size: 0
		public const int BC_BARRACKNAME_CHANGE = 0x1d; // Size: 79
		public const int CB_VISIT = 0x38; // Size: 88
		public const int CB_BUY_THEMA = 0x39; // Size: 34
		public const int BC_ACCOUNT_PROP = 0x3a; // Size: 0
		public const int CB_CURRENT_BARRACK = 0x3b; // Size: 51
		public const int CB_GEMSCOOL_PCINFO = 0x52; // Size: 1302
		public const int BC_NORMAL = 0x3c; // Size: 0
		public const int CB_POSE = 0x3d; // Size: 27
		public const int CB_PLACE_CMD = 0x3e; // Size: 58
		public const int CB_CHAT = 0x3f; // Size: 0
		public const int BC_CHAT = 0x40; // Size: 0
		public const int CB_ECHO_NORMAL = 0x41; // Size: 0
		public const int CB_JUMP = 0x48; // Size: 31
		public const int BC_JUMP = 0x49; // Size: 31
		public const int BC_SERVER_ENTRY = 0x4a; // Size: 22
		public const int CB_PET_PC = 0x4b; // Size: 38
		public const int CB_PET_COMMAND = 0x4c; // Size: 39
		public const int CB_CHANGE_BARRACK_LAYER = 0x44; // Size: 34
		public const int CB_CHANGE_BARRACK_TARGET_LAYER = 0x45; // Size: 34
		public const int CB_SELECT_BARRACK_LAYER = 0x46; // Size: 26
		public const int CB_SCREENSHOT_HASH = 0x36; // Size: 54
		public const int CB_REQ_SLOT_PRICE = 0x42; // Size: 22
		public const int BC_REQ_SLOT_PRICE = 0x43; // Size: 14
		public const int CB_REQ_CHANGE_POSTBOX_STATE = 0x4d; // Size: 35
		public const int CB_REQ_POSTBOX_PAGE = 0x4f; // Size: 26
		public const int CB_REQ_GET_POSTBOX_ITEM = 0x4e; // Size: 1063
		public const int BC_WAIT_QUEUE_ORDER = 0x50; // Size: 14
		public const int CB_CANCEL_SERVER_WAIT_QUEUE = 0x51; // Size: 22
		public const int CB_REQ_CHANNEL_TRAFFIC = 0x37; // Size: 26
		public const int CB_DEBUG_LOG_FILE = 0x54; // Size: 0
		public const int BC_FAIL_TO_GET_AUTHCODE = 0x55; // Size: 16
		public const int CB_CLIENT_REMOTE_LOG = 0x56; // Size: 2584
		public const int BC_RETURN_PC_MARKET_REGISTERED = 0x58; // Size: 20
		public const int BC_CHARACTER_SLOT_SWAP_SUCCESS = 0x59; // Size: 16
		public const int CB_CHARACTER_SWAP_SLOT = 0x5a; // Size: 38
		public const int BC_CHARACTER_SLOT_SWAP_FAIL = 0x5b; // Size: 16
		public const int BC_LAYER_CHANGE_SYSTEM_MESSAGE = 0x47; // Size: 78
		public const int BC_DISCONNECT_PACKET_LOG_COUNT = 0x5c; // Size: 14
		public const int CB_REQ_POSTBOX_REFRESH = 0x5d; // Size: 22
		public const int CS_LOGIN = 0x3e1d; // Size: 91
		public const int SC_NORMAL = 0x3e1e; // Size: 0
		public const int SC_FROM_INTEGRATE = 0x3e1f; // Size: 0
		public const int CS_REGISTER_SNS_ID = 0x3e20; // Size: 24
		public const int CS_REQ_SNS_PC_INFO = 0x3e21; // Size: 0
		public const int CS_REQ_ADD_FRIEND = 0x3e22; // Size: 74
		public const int CS_REQ_BLOCK_FRIEND = 0x3e23; // Size: 74
		public const int CS_FRIEND_CMD = 0x3e24; // Size: 32
		public const int CS_FRIEND_SET_ADDINFO = 0x3e25; // Size: 168
		public const int CS_CHAT = 0x3e26; // Size: 0
		public const int CS_GROUP_CHAT_INVITE = 0x3e27; // Size: 114
		public const int CS_GROUP_CHAT_INVITE_BY_TAG = 0x3e28; // Size: 26
		public const int CS_ALLOW_GROUP_CHAT_TAG_INVITE = 0x3e29; // Size: 50
		public const int CS_REFRESH_GROUP_CHAT = 0x3e2a; // Size: 16
		public const int CS_REQ_CHAT_HISTORY = 0x3e2c; // Size: 26
		public const int CS_REQ_OUT_ROOM = 0x3e2d; // Size: 18
		public const int CS_ADD_RELATION_SCORE = 0x3e39; // Size: 96
		public const int CS_GET_LIKE_COUNT = 0x3e3a; // Size: 24
		public const int CS_LIKE_IT = 0x3e36; // Size: 96
		public const int CS_UNLIKE_IT = 0x3e37; // Size: 32
		public const int CS_LIKE_IT_CONFIRM = 0x3e38; // Size: 24
		public const int CS_REQ_RELATED_PC_SESSION = 0x3e2e; // Size: 24
		public const int CS_REDIS_SKILLPOINT = 0x3e2f; // Size: 26
		public const int CS_CREATE_GROUP_CHAT = 0x3e2b; // Size: 16
		public const int CS_PARTY_CLIENT_INFO_SEND = 0x3e30; // Size: 0
		public const int CS_NORMAL_GAME_START = 0x3e31; // Size: 16
		public const int CS_REQUEST_PVP_RANKING = 0x3e32; // Size: 92
		public const int CS_REQUEST_ALL_SEASON_TOP_PVP_RANKING = 0x3e33; // Size: 84
		public const int CS_INVITE_PARTY_PVP = 0x3e34; // Size: 14
		public const int CS_ACCEPT_PARTY_PVP = 0x3e35; // Size: 23
		public const int CS_REQ_MEMBER_LOGOUT_TIME = 0x3e3b; // Size: 16
		public const int CS_INVITE_GROUPCHAT_ACCEPT = 0x3e3c; // Size: 135
		public const int CZ_CONNECT = 0xbb9; // Size: 1268
		public const int CZ_GAME_READY = 0xbbe; // Size: 22
		public const int ZC_ADD_BARRACK_CHARACTER_SLOT_SUCCESS = 0xe39; // Size: 18
		public const int CZ_KEYBOARD_MOVE = 0xc5e; // Size: 66
		public const int CZ_EXPECTED_STOP_POS = 0xc5f; // Size: 43
		public const int CZ_MOVE_PATH = 0xc63; // Size: 39
		public const int CZ_MOVE_STOP = 0xc64; // Size: 60
		public const int CZ_JUMP = 0xc60; // Size: 60
		public const int CZ_DASHRUN = 0xc61; // Size: 24
		public const int CZ_REST_SIT = 0xc65; // Size: 22
		public const int CZ_REQ_CHAR_SLOT = 0xc66; // Size: 23
		public const int CZ_ON_AIR = 0xc67; // Size: 22
		public const int CZ_ON_GROUND = 0xc68; // Size: 22
		public const int CZ_SKILL_JUMP_REQ = 0xc62; // Size: 42
		public const int CZ_LOGOUT = 0xbc0; // Size: 23
		public const int CZ_MOVE_BARRACK = 0xbc1; // Size: 31
		public const int CZ_MOVE_ZONE_OK = 0xbbc; // Size: 22
		public const int CZ_MOVEMENT_INFO = 0xc69; // Size: 35
		public const int CZ_NOTICE_GUILD_APPLICATION_REQUEST = 0xf01; // Size: 32
		public const int CZ_PARTY_OUT = 0xcda; // Size: 22
		public const int CZ_NGS = 0xe12; // Size: 0
		public const int ZC_NGS = 0xe13; // Size: 0
		public const int CZ_REQ_GM_ORDER_DUMMY_KICK = 0xe28; // Size: 26
		public const int CZ_SKILL_TARGET = 0xc6a; // Size: 32
		public const int CZ_SKILL_TARGET_ANI = 0xc6b; // Size: 36
		public const int CZ_SKILL_GROUND = 0xc6c; // Size: 79
		public const int CZ_SKILL_SELF = 0xc6d; // Size: 48
		public const int CZ_SKILL_CANCEL = 0xc6e; // Size: 24
		public const int CZ_HOLD = 0xc6f; // Size: 23
		public const int CZ_SHOUT = 0xc77; // Size: 0
		public const int CZ_CHAT = 0xc74; // Size: 0
		public const int CZ_SELF_CHAT = 0xc75; // Size: 0
		public const int CZ_CHAT_LOG = 0xc76; // Size: 0
		public const int CZ_ITEM_USE = 0xc7a; // Size: 34
		public const int CZ_ITEM_USE_TO_ITEM = 0xc7b; // Size: 42
		public const int CZ_ITEM_USE_TO_GROUND = 0xc7c; // Size: 42
		public const int CZ_ITEM_DROP = 0xc78; // Size: 34
		public const int CZ_ITEM_EQUIP = 0xc7f; // Size: 31
		public const int CZ_ITEM_UNEQUIP = 0xc80; // Size: 23
		public const int CZ_REQ_DELETE_EXPIRED_ITEMS = 0xc81; // Size: 30
		public const int ZC_CHECK_INVINDEX = 0xc82; // Size: 34
		public const int CZ_ITEM_DELETE = 0xc79; // Size: 38
		public const int CZ_ITEM_BUY = 0xc7d; // Size: 0
		public const int CZ_ITEM_SELL = 0xc7e; // Size: 0
		public const int CZ_ITEMPROPCHANGE = 0xed3; // Size: 38
		public const int CZ_ITEMPROPCHANGE_GEM_ADD = 0xed4; // Size: 26
		public const int CZ_ITEMPROPCHANGE_GEM_DROP = 0xed5; // Size: 50
		public const int CZ_ITEMPROPCHANGE_GEM_POP = 0xed6; // Size: 34
		public const int CZ_ITEMPROPCHANGE_GEM_ALL_SLOT = 0xed7; // Size: 30
		public const int CZ_ITEMPROPCHANGE_ICHOR_RANDOM_OPTION = 0xed8; // Size: 166
		public const int CZ_ITEMPROPCHANGE_ICHOR_RANDOM_OPTION_MAX_VALUE = 0xed9; // Size: 98
		public const int CZ_ITEMPROPCHANGE_OPTION_CHANGE = 0xeda; // Size: 94
		public const int CZ_DIALOG_ACK = 0xc9e; // Size: 26
		public const int CZ_DIALOG_SELECT = 0xc9f; // Size: 23
		public const int CZ_DIALOG_STRINGINPUT = 0xca0; // Size: 150
		public const int CZ_MOVE_CAMP = 0xcb3; // Size: 30
		public const int CZ_CAMPINFO = 0xcb4; // Size: 30
		public const int ZC_CAMPINFO = 0xcb5; // Size: 22
		public const int CZ_HOUSING_OPEN_EDIT_MODE = 0xf3e; // Size: 16
		public const int CZ_HOUSING_CLOSE_EDIT_MODE = 0xf3f; // Size: 16
		public const int CZ_HOUSING_REQUEST_GRID_ARRANGED_FURNITURE = 0xf40; // Size: 22
		public const int ZC_HOUSING_READY_GRID = 0xf41; // Size: 0
		public const int ZC_HOUSING_READY_ARRANGED_FURNITURE = 0xf42; // Size: 0
		public const int ZC_HOUSING_START_ARRANGEMENT_FURNITURE = 0xf43; // Size: 14
		public const int CZ_HOUSING_REQUEST_ARRANGEMENT_FURNITURE = 0xf44; // Size: 0
		public const int CZ_HOUSING_CANCEL_ARRANGEMENT_FURNITURE = 0xf45; // Size: 23
		public const int CZ_HOUSING_REQUEST_REMOVE_FURNITURE = 0xf46; // Size: 30
		public const int CZ_HOUSING_REQUEST_REMOVE_FURNITURE_ALOT = 0xf47; // Size: 0
		public const int CZ_HOUSING_REQUEST_REMOVE_ALL_FURNITURE = 0xf48; // Size: 22
		public const int ZC_HOUSING_ANSWER_REMOVE_FURNITURE = 0xf49; // Size: 18
		public const int CZ_HOUSING_REQUEST_ENABLE_MOVE_FURNITURE = 0xf4a; // Size: 30
		public const int ZC_HOUSING_ANSWER_ENABLE_MOVE_FURNITURE = 0xf4b; // Size: 18
		public const int CZ_HOUSING_REQUEST_MOVE_FURNITURE = 0xf4c; // Size: 0
		public const int CZ_HOUSING_REQUEST_GUILD_AGIT_INFO = 0xf4d; // Size: 158
		public const int ZC_HOUSING_ANSWER_GUILD_AGIT_INFO = 0xf4e; // Size: 138
		public const int CZ_HOUSING_REQUEST_GUILD_AGIT_EXTENSION = 0xf4f; // Size: 150
		public const int CZ_HOUSING_REQUEST_GUILD_LAB_USE_RESEARCH = 0xf50; // Size: 27
		public const int CZ_HOUSING_REQUEST_GUILD_LAB_LEVEL_UP = 0xf51; // Size: 27
		public const int CZ_HOUSING_REQUEST_GUILD_LAB_RESEARCH_LEVEL_UP = 0xf52; // Size: 26
		public const int CZ_HOUSING_REQUEST_GUILD_CONTRIBUTION_TO_MILEAGE = 0xf53; // Size: 26
		public const int CZ_HOUSING_REQUEST_GUILD_MILEAGE_TO_CONTRIBUTION = 0xf54; // Size: 26
		public const int CZ_HOUSING_REQUEST_GUILD_CONTIRUBTION_DISTRIBUTE = 0xf55; // Size: 0
		public const int CZ_HOUSING_REQUEST_GUILD_POINT_UP = 0xf56; // Size: 166
		public const int CZ_HOUSING_REQUEST_HOUSING_SHOP_TRADE = 0xf57; // Size: 0
		public const int ZC_HOUSING_CREATE_BG_FURNITURE = 0xf58; // Size: 31
		public const int ZC_HOUSING_MOVE_BG_FURNITURE = 0xf59; // Size: 27
		public const int ZC_HOUSING_REMOVE_BG_FURNITURE = 0xf5a; // Size: 14
		public const int CZ_HOUSING_PAGE_SAVE = 0xf5b; // Size: 90
		public const int CZ_HOUSING_PAGE_LOAD = 0xf5c; // Size: 26
		public const int CZ_HOUSING_PAGE_DELETE = 0xf5d; // Size: 26
		public const int CZ_PERSONAL_HOUSING_REQUEST_LEAVE = 0xf5e; // Size: 22
		public const int CZ_PERSONAL_HOUSING_REQUEST_BUY_BACKGROUND = 0xf5f; // Size: 26
		public const int CZ_PERSONAL_HOUSING_REQUEST_APPLY_BACKGROUND = 0xf60; // Size: 26
		public const int CZ_HOUSING_REQUEST_PREVIEW = 0xf61; // Size: 39
		public const int ZC_HOUSING_ANSWER_PREVIEW = 0xf62; // Size: 0
		public const int ZC_ANCIENT_MON_REG = 0xf64; // Size: 226
		public const int ZC_ANCIENT_MON_UPDATE = 0xf65; // Size: 113
		public const int ZC_ANCIENT_MON_LOAD = 0xf66; // Size: 0
		public const int ZC_ANCIENT_MON_EXP_UP = 0xf67; // Size: 42
		public const int CZ_ANCIENT_MON_COMPOSE = 0xf6b; // Size: 50
		public const int CZ_ANCIENT_MON_SELL = 0xf68; // Size: 30
		public const int CZ_ANCIENT_MON_SWAP = 0xf69; // Size: 34
		public const int CZ_ANCIENT_MON_ALLKILL = 0xf6a; // Size: 22
		public const int CZ_CLICK_TRIGGER = 0xc5d; // Size: 27
		public const int CZ_ROTATE = 0xc70; // Size: 30
		public const int CZ_HEAD_ROTATE = 0xc71; // Size: 30
		public const int CZ_TARGET_ROTATE = 0xc72; // Size: 30
		public const int CZ_POSE = 0xc73; // Size: 47
		public const int CZ_SYSTEM_LOG_TO_SERVER = 0xe16; // Size: 1111
		public const int CZ_CANCEL_INDUN_MATCHING = 0xe25; // Size: 22
		public const int CZ_CANCEL_INDUN_PARTY_MATCHING = 0xe26; // Size: 22
		public const int CZ_PARTY_SHARED_QUEST = 0xe2c; // Size: 290
		public const int CZ_REQ_FORGERY = 0xe46; // Size: 42
		public const int CZ_REQ_BUILD_FOODTABLE = 0xe49; // Size: 94
		public const int CZ_REQ_FISHING = 0xe4b; // Size: 35
		public const int CZ_REQ_GET_FISHING_ITEM = 0xe4c; // Size: 22
		public const int CZ_REQ_FISHING_RANK = 0xe54; // Size: 90
		public const int ZC_ENABLE_ROTATE = 0xe55; // Size: 79
		public const int CZ_REQ_ADVENTURE_BOOK_RANK = 0xe59; // Size: 154
		public const int CZ_REQ_ADVENTURE_BOOK_REWARD = 0xe5a; // Size: 86
		public const int CZ_REQ_QUEST_COMPLETE = 0xe5c; // Size: 26
		public const int CZ_REQ_GUILD_ASSET_LOG = 0xe5d; // Size: 22
		public const int CZ_REQ_COMMON_SKILL_LIST = 0xeb4; // Size: 22
		public const int CZ_REG_EXP_ORB_ITEM = 0xeb6; // Size: 30
		public const int ZC_REG_EXP_ORB_ITEM = 0xeb8; // Size: 22
		public const int ZC_FILL_EXP_ORB = 0xeb9; // Size: 22
		public const int CZ_REQ_QUICKSLOT_LIST = 0xeb7; // Size: 22
		public const int ZC_ENTER_PC = 0xc1d; // Size: 530
		public const int ZC_ENTER_MONSTER = 0xc1e; // Size: 0
		public const int ZC_ENTER_DUMMYPC = 0xc1f; // Size: 488
		public const int ZC_UPDATED_DUMMYPC = 0xc20; // Size: 446
		public const int ZC_ENTER_ITEM = 0xc21; // Size: 107
		public const int ZC_LEAVE = 0xc22; // Size: 16
		public const int ZC_MOVE_PATH = 0xc23; // Size: 46
		public const int ZC_MOVE_POS = 0xc24; // Size: 50
		public const int ZC_MOVE_BEZIER = 0xc25; // Size: 79
		public const int ZC_MSPD = 0xc28; // Size: 26
		public const int ZC_MOVE_SPEED = 0xc29; // Size: 31
		public const int ZC_MOVE_DIR = 0xc26; // Size: 65
		public const int ZC_EXPECTED_STOPPOS = 0xc27; // Size: 39
		public const int ZC_MOVE_STOP = 0xc2a; // Size: 27
		public const int ZC_REST_SIT = 0xc2b; // Size: 16
		public const int ZC_JUMP = 0xc2c; // Size: 60
		public const int ZC_JUMP_DIR = 0xc2d; // Size: 55
		public const int ZC_ORDER_SKILL_JUMP = 0xc2e; // Size: 14
		public const int ZC_SKILL_JUMP = 0xc2f; // Size: 42
		public const int ZC_SET_POS = 0xc30; // Size: 27
		public const int ZC_FILE_MOVE = 0xc31; // Size: 50
		public const int ZC_MESSAGE = 0xbc4; // Size: 0
		public const int ZC_CONNECT_OK = 0xbba; // Size: 0
		public const int ZC_CONNECT_FAILED = 0xbbd; // Size: 0
		public const int ZC_START_GAME = 0xbc6; // Size: 30
		public const int ZC_MOVE_ZONE = 0xbbb; // Size: 11
		public const int ZC_MOVE_BARRACK = 0xbc2; // Size: 16
		public const int ZC_MOVE_ZONE_OK = 0xbbf; // Size: 61
		public const int ZC_DEAD = 0xc4f; // Size: 0
		public const int ZC_RESURRECT = 0xc50; // Size: 22
		public const int ZC_RESURRECT_DIALOG = 0xc52; // Size: 14
		public const int CZ_RESURRECT = 0xc5a; // Size: 31
		public const int ZC_RESURRECT_SAVE_POINT_ACK = 0xc5b; // Size: 11
		public const int ZC_RESURRECT_HERE_ACK = 0xc5c; // Size: 11
		public const int ZC_UPDATED_PCAPPEARANCE = 0xc32; // Size: 446
		public const int ZC_UPDATED_MONSTERAPPEARANCE = 0xc33; // Size: 0
		public const int ZC_ADD_HP = 0xc37; // Size: 26
		public const int ZC_UPDATE_SP = 0xc9b; // Size: 19
		public const int ZC_UPDATE_MHP = 0xc9d; // Size: 18
		public const int ZC_EXP_UP = 0xc95; // Size: 26
		public const int ZC_EXP_UP_BY_MONSTER = 0xc96; // Size: 30
		public const int ZC_PC_LEVELUP = 0xc97; // Size: 18
		public const int ZC_PC_STAT_AVG = 0xc98; // Size: 34
		public const int ZC_MAX_EXP_CHANGED = 0xc99; // Size: 38
		public const int ZC_UPDATE_ALL_STATUS = 0xcbe; // Size: 34
		public const int ZC_CHANGE_RELATION = 0xc51; // Size: 15
		public const int ZC_QUICK_SLOT_LIST = 0xc8e; // Size: 0
		public const int ZC_SKILL_LIST = 0xc8f; // Size: 0
		public const int ZC_SKILL_ADD = 0xc90; // Size: 0
		public const int ZC_SKILL_REMOVE = 0xc91; // Size: 18
		public const int ZC_SKILL_CAST_CANCEL = 0xc38; // Size: 14
		public const int ZC_SKILL_CAST = 0xc39; // Size: 42
		public const int ZC_SKILL_READY = 0xc3a; // Size: 54
		public const int ZC_SKILL_USE_CANCEL = 0xc3c; // Size: 14
		public const int ZC_SKILL_DISABLE = 0xc3b; // Size: 19
		public const int ZC_SKILL_MELEE_TARGET = 0xc3d; // Size: 0
		public const int ZC_SKILL_FORCE_TARGET = 0xc3f; // Size: 0
		public const int ZC_SKILL_MELEE_GROUND = 0xc3e; // Size: 0
		public const int ZC_SKILL_FORCE_GROUND = 0xc40; // Size: 0
		public const int ZC_SKILL_HIT_INFO = 0xc41; // Size: 0
		public const int ZC_COMMON_SKILL_LIST = 0xeb5; // Size: 0
		public const int ZC_ABILITY_LIST = 0xc92; // Size: 0
		public const int CZ_DISPEL_DEBUFF_TOGGLE = 0xc93; // Size: 26
		public const int CZ_JUNGTAN_TOGGLE = 0xc94; // Size: 36
		public const int ZC_BUFF_LIST = 0xc42; // Size: 0
		public const int ZC_BUFF_ADD = 0xc43; // Size: 0
		public const int ZC_BUFF_UPDATE = 0xc44; // Size: 0
		public const int ZC_BUFF_REMOVE = 0xc45; // Size: 24
		public const int ZC_BUFF_CLEAR = 0xc46; // Size: 15
		public const int CZ_BUFF_REMOVE = 0xc47; // Size: 26
		public const int CZ_INTE_WARP = 0xc48; // Size: 26
		public const int ZC_HIT_INFO = 0xc53; // Size: 74
		public const int ZC_HEAL_INFO = 0xc54; // Size: 38
		public const int ZC_CAUTION_DAMAGE_INFO = 0xc56; // Size: 19
		public const int ZC_CAUTION_DAMAGE_RELEASE = 0xc57; // Size: 14
		public const int ZC_KNOCKBACK_INFO = 0xc58; // Size: 74
		public const int ZC_KNOCKDOWN_INFO = 0xc59; // Size: 75
		public const int ZC_CHAT = 0xc34; // Size: 0
		public const int ZC_CHAT_WITH_TEXTCODE = 0xc35; // Size: 18
		public const int ZC_SHOUT = 0xcc1; // Size: 0
		public const int ZC_SHOUT_FAILED = 0xcc2; // Size: 11
		public const int ZC_TEXT = 0xc9a; // Size: 0
		public const int ZC_QUIET = 0xbc7; // Size: 11
		public const int ZC_DIALOG_CLOSE = 0xca5; // Size: 16
		public const int ZC_DIALOG_OK = 0xca1; // Size: 0
		public const int ZC_DIALOG_NEXT = 0xca2; // Size: 0
		public const int ZC_DIALOG_SELECT = 0xca3; // Size: 0
		public const int ZC_DIALOG_TRADE = 0xca6; // Size: 43
		public const int ZC_DIALOG_COMMON_TRADE = 0xca7; // Size: 43
		public const int ZC_DIALOG_ITEM_SELECT = 0xca4; // Size: 0
		public const int ZC_DIALOG_NUMBERRANGE = 0xca8; // Size: 0
		public const int ZC_DIALOG_STRINGINPUT = 0xca9; // Size: 0
		public const int ZC_STANCE_CHANGE = 0xc36; // Size: 18
		public const int ZC_ITEM_ADD = 0xc8a; // Size: 0
		public const int ZC_ITEM_INVENTORY_LIST = 0xc86; // Size: 0
		public const int ZC_ITEM_INVENTORY_DIVISION_LIST = 0xc87; // Size: 0
		public const int ZC_ITEM_INVENTORY_INDEX_LIST = 0xc88; // Size: 0
		public const int ZC_ITEM_EQUIP_LIST = 0xc89; // Size: 0
		public const int ZC_ITEM_REMOVE = 0xc8b; // Size: 28
		public const int ZC_ITEM_USE = 0xc8c; // Size: 18
		public const int ZC_ITEM_USE_TO_GROUND = 0xc8d; // Size: 26
		public const int ZC_RESET_VIEW = 0xbc5; // Size: 16
		public const int ZC_RESTORATION = 0xc9c; // Size: 16
		public const int ZC_ROTATE = 0xc49; // Size: 24
		public const int ZC_ROTATE_RESERVED = 0xc4a; // Size: 22
		public const int ZC_HEAD_ROTATE = 0xc4b; // Size: 22
		public const int ZC_TARGET_ROTATE = 0xc4c; // Size: 22
		public const int ZC_QUICK_ROTATE = 0xc4d; // Size: 22
		public const int ZC_POSE = 0xc4e; // Size: 39
		public const int ZC_DELAYED_ROTATE_MOVE_START = 0xe6a; // Size: 26
		public const int ZC_DELAYED_ROTATE_MOVE_END = 0xe6b; // Size: 14
		public const int ZC_DUMP_PROPERTY = 0xcc0; // Size: 0
		public const int ZC_OBJECT_PROPERTY = 0xcbf; // Size: 0
		public const int ZC_OBJECT_PROPERTY_BY_NAMES = 0xeff; // Size: 0
		public const int ZC_ADDON_MSG = 0xcaa; // Size: 0
		public const int CZ_UI_EVENT = 0xcab; // Size: 0
		public const int ZC_LOGOUT_OK = 0xbc3; // Size: 16
		public const int ZC_PLAY_SOUND = 0xcac; // Size: 19
		public const int ZC_STOP_SOUND = 0xcad; // Size: 18
		public const int ZC_PLAY_MUSICQUEUE = 0xcae; // Size: 20
		public const int ZC_STOP_MUSICQUEUE = 0xcaf; // Size: 18
		public const int ZC_PLAY_ANI = 0xcb0; // Size: 28
		public const int ZC_PLAY_ANI_SELFISH = 0xcb1; // Size: 23
		public const int ZC_CHANGE_ANI = 0xcb2; // Size: 48
		public const int ZC_PLAY_ALARMSOUND = 0xcba; // Size: 87
		public const int ZC_STOP_ALARMSOUND = 0xcbb; // Size: 14
		public const int ZC_PLAY_EXP_TEXT = 0xcbc; // Size: 18
		public const int ZC_PLAY_NAVI_EFFECT = 0xcbd; // Size: 154
		public const int CZ_EXCHANGE_REQUEST = 0xcc3; // Size: 26
		public const int ZC_EXCHANGE_REQUEST_ACK = 0xcc4; // Size: 76
		public const int ZC_EXCHANGE_REQUEST_RECEIVED = 0xcc5; // Size: 75
		public const int CZ_EXCHANGE_ACCEPT = 0xcc6; // Size: 22
		public const int CZ_EXCHANGE_DECLINE = 0xcc7; // Size: 22
		public const int ZC_EXCHANGE_DECLINE_ACK = 0xcc8; // Size: 16
		public const int ZC_EXCHANGE_START = 0xcc9; // Size: 76
		public const int CZ_EXCHANGE_OFFER = 0xcca; // Size: 42
		public const int ZC_EXCHANGE_OFFER_ACK = 0xccb; // Size: 0
		public const int CZ_EXCHANGE_AGREE = 0xccc; // Size: 22
		public const int ZC_EXCHANGE_AGREE_ACK = 0xccd; // Size: 11
		public const int CZ_EXCHANGE_FINALAGREE = 0xcce; // Size: 22
		public const int ZC_EXCHANGE_FINALAGREE_ACK = 0xccf; // Size: 11
		public const int CZ_EXCHANGE_CANCEL = 0xcd0; // Size: 22
		public const int ZC_EXCHANGE_CANCEL_ACK = 0xcd1; // Size: 16
		public const int ZC_EXCHANGE_SUCCESS = 0xcd2; // Size: 16
		public const int ZC_COOLDOWN_LIST = 0xcd3; // Size: 0
		public const int ZC_COOLDOWN_CHANGED = 0xcd4; // Size: 31
		public const int ZC_OVERHEAT_CHANGED = 0xcd5; // Size: 46
		public const int ZC_TEST_AGENT = 0xcd6; // Size: 22
		public const int ZC_TIME_FACTOR = 0xcd7; // Size: 14
		public const int ZC_PARTY_ENTER = 0xcd8; // Size: 0
		public const int ZC_PARTY_OUT = 0xcd9; // Size: 28
		public const int ZC_PARTY_DESTROY = 0xcdb; // Size: 19
		public const int ZC_PARTY_INFO = 0xcdc; // Size: 0
		public const int ZC_PARTY_LIST = 0xcdd; // Size: 0
		public const int ZC_PARTY_INST_INFO = 0xcde; // Size: 0
		public const int ZC_CHANGE_DYNAMICCASTING_MAX_CHANGING_TIME = 0xe69; // Size: 18
		public const int ZC_CHANGE_EQUIP_DURABILITY = 0xcdf; // Size: 15
		public const int CZ_DIALOG_TX = 0xce1; // Size: 0
		public const int CZ_REQ_RECIPE = 0xce2; // Size: 0
		public const int ZC_CUSTOM_DIALOG = 0xce3; // Size: 79
		public const int ZC_SESSION_OBJECTS = 0xce4; // Size: 0
		public const int ZC_SESSION_OBJ_ADD = 0xce5; // Size: 0
		public const int ZC_SESSION_OBJ_REMOVE = 0xce6; // Size: 14
		public const int ZC_SESSION_OBJ_TIME = 0xce7; // Size: 18
		public const int CZ_S_OBJ_VALUE_C = 0xce8; // Size: 38
		public const int CZ_REQ_NORMAL_TX = 0xce9; // Size: 57
		public const int ZC_COMMANDER_LOADER_INFO = 0xcea; // Size: 0
		public const int ZC_MOVE_SINGLE_ZONE = 0xceb; // Size: 22
		public const int ZC_BACKTO_ORIGINAL_SERVER = 0xcec; // Size: 12
		public const int CZ_BACKTO_ORIGINAL_SERVER = 0xced; // Size: 24
		public const int CZ_REQ_NORMAL_TX_NUMARG = 0xcee; // Size: 0
		public const int ZC_UI_OPEN = 0xcef; // Size: 43
		public const int ZC_ENABLE_CONTROL = 0xcf0; // Size: 79
		public const int ZC_CHANGE_CAMERA = 0xcf1; // Size: 35
		public const int ZC_MONSTER_SDR_CHANGED = 0xcf2; // Size: 15
		public const int ZC_MOVE_IGNORE_COLLISION = 0xcf3; // Size: 34
		public const int ZC_CHANGE_CAMERA_ZOOM = 0xcf4; // Size: 42
		public const int ZC_PLAY_SKILL_ANI = 0xcf5; // Size: 86
		public const int ZC_PLAY_SKILL_CAST_ANI = 0xcf6; // Size: 34
		public const int CZ_REQ_ITEM_GET = 0xcf7; // Size: 26
		public const int ZC_ITEM_GET = 0xcf8; // Size: 22
		public const int CZ_GUARD = 0xcf9; // Size: 31
		public const int ZC_GUARD = 0xcfa; // Size: 23
		public const int ZC_STAMINA = 0xcfb; // Size: 14
		public const int ZC_ADD_STAMINA = 0xcfc; // Size: 14
		public const int ZC_GM_ORDER = 0xcfd; // Size: 14
		public const int ZC_MYPC_ENTER = 0xcfe; // Size: 27
		public const int ZC_LOCK_KEY = 0xcff; // Size: 79
		public const int CZ_PREMIUM_ENCHANTCHIP = 0xc83; // Size: 38
		public const int CZ_PREMIUM_GACHACUBE = 0xc84; // Size: 22
		public const int CZ_PREMIUM_GACHACUBE_LEGEND = 0xc85; // Size: 23
		public const int ZC_SAVE_INFO = 0xd00; // Size: 16
		public const int CZ_SAVE_INFO = 0xd01; // Size: 0
		public const int ZC_OPTION_LIST = 0xd02; // Size: 0
		public const int ZC_SKILLMAP_LIST = 0xd03; // Size: 0
		public const int CZ_FOOD_TABLE_TITLE = 0xd05; // Size: 91
		public const int CZ_USE_TP_AND_ENTER_INDUN = 0xd06; // Size: 534
		public const int CZ_USE_RANKRESET_ITEM = 0xd07; // Size: 32
		public const int CZ_REQ_RANKRESET_SYSTEM = 0xd08; // Size: 26
		public const int CZ_GIVEITEM_TO_DUMMYPC = 0xd04; // Size: 34
		public const int ZC_SET_LAYER = 0xd09; // Size: 15
		public const int ZC_CREATE_LAYERBOX = 0xd0a; // Size: 42
		public const int ZC_RESET_BOX = 0xd0b; // Size: 15
		public const int ZC_CREATE_SCROLLLOCKBOX = 0xd0c; // Size: 42
		public const int ZC_REMOVE_SCROLLLOCKBOX = 0xd0d; // Size: 14
		public const int CZ_DYNAMIC_CASTING_START = 0xd0e; // Size: 51
		public const int CZ_DYNAMIC_CASTING_END = 0xd0f; // Size: 33
		public const int ZC_CASTING_SPEED = 0xd10; // Size: 26
		public const int CZ_SKILL_CANCEL_SCRIPT = 0xd11; // Size: 22
		public const int ZC_LEAVE_TRIGGER = 0xd12; // Size: 16
		public const int ZC_BORN = 0xd13; // Size: 14
		public const int ZC_ACHIEVE_POINT_LIST = 0xd14; // Size: 0
		public const int ZC_ACHIEVE_POINT = 0xd15; // Size: 22
		public const int CZ_ACHIEVE_EQUIP = 0xd16; // Size: 26
		public const int ZC_ACHIEVE_EQUIP = 0xd17; // Size: 34
		public const int CZ_ACHIEVE_REWARD = 0xd18; // Size: 26
		public const int CZ_CHANGE_CONFIG = 0xd19; // Size: 30
		public const int CZ_CHANGE_CONFIG_STR = 0xd1a; // Size: 46
		public const int ZC_WORLD_MSG = 0xd1b; // Size: 47
		public const int ZC_ENABLE_SHOW_ITEM_GET = 0xd1c; // Size: 12
		public const int ZC_LOGIN_TIME = 0xd1d; // Size: 18
		public const int ZC_GIVE_EXP_TO_PC = 0xd1e; // Size: 50
		public const int ZC_LAYER_PC_LIST = 0xd1f; // Size: 0
		public const int ZC_LAYER_PC_SOBJ_PROP = 0xd20; // Size: 0
		public const int CZ_CUSTOM_COMMAND = 0xd21; // Size: 38
		public const int CZ_ADD_HELP = 0xdb8; // Size: 26
		public const int ZC_LAYER_INFO = 0xd22; // Size: 14
		public const int CZ_CHAT_MACRO = 0xd23; // Size: 158
		public const int ZC_CHAT_MACRO_LIST = 0xd24; // Size: 0
		public const int ZC_RULLET_LIST = 0xd25; // Size: 0
		public const int ZC_QUICKSLOT_REGISTER = 0xd26; // Size: 50
		public const int CZ_QUICKSLOT_LIST = 0xd27; // Size: 0
		public const int CZ_DOUBLE_ITEM_EQUIP = 0xd28; // Size: 40
		public const int ZC_TRICK_PACKET = 0xd29; // Size: 0
		public const int ZC_COOLDOWN_RATE = 0xd2a; // Size: 26
		public const int ZC_MAP_REVEAL_LIST = 0xd2b; // Size: 0
		public const int CZ_MAP_REVEAL_INFO = 0xd2c; // Size: 158
		public const int CZ_MAP_SEARCH_INFO = 0xd2d; // Size: 67
		public const int ZC_EXEC_CLIENT_SCP = 0xd2e; // Size: 0
		public const int ZC_SET_NPC_STATE = 0xd2f; // Size: 22
		public const int ZC_NPC_STATE_LIST = 0xd30; // Size: 0
		public const int CZ_QUEST_NPC_STATE_CHECK = 0xd31; // Size: 26
		public const int ZC_RANK_ACHIEVE_ADD = 0xd32; // Size: 18
		public const int CZ_IES_MODIFY_INFO = 0xd33; // Size: 0
		public const int ZC_IES_MODIFY_INFO = 0xd34; // Size: 0
		public const int ZC_IES_MODIFY_LIST = 0xd35; // Size: 0
		public const int CZ_IES_REVISION_DELETE = 0xd36; // Size: 0
		public const int ZC_IES_REVISION_DELETE = 0xd37; // Size: 0
		public const int ZC_EQUIP_ITEM_REMOVE = 0xd38; // Size: 22
		public const int ZC_SOLD_ITEM_LIST = 0xd39; // Size: 0
		public const int ZC_SOLD_ITEM_DIVISION_LIST = 0xd3a; // Size: 0
		public const int CZ_SOLD_ITEM = 0xd3b; // Size: 31
		public const int CZ_WAREHOUSE_CMD = 0xd3c; // Size: 48
		public const int CZ_SWAP_ETC_INV_CHANGE_INDEX = 0xd3d; // Size: 47
		public const int CZ_SORT_INV = 0xd3e; // Size: 24
		public const int CZ_EXTEND_WAREHOUSE = 0xd3f; // Size: 23
		public const int CZ_CAST_CONTROL_SHOT = 0xd40; // Size: 22
		public const int ZC_PC_PROP_UPDATE = 0xd41; // Size: 15
		public const int ZC_SHOP_POINT_UPDATE = 0xd42; // Size: 58
		public const int CZ_SHOP_POINT_GET = 0xd43; // Size: 54
		public const int CZ_CLIENT_DAMAGE = 0xd44; // Size: 26
		public const int CZ_CLIENT_ATTACK = 0xd45; // Size: 27
		public const int ZC_SYSTEM_MSG = 0xd46; // Size: 0
		public const int ZC_FSM_MOVE = 0xd47; // Size: 0
		public const int CZ_QUEST_CHECK_SAVE = 0xd48; // Size: 62
		public const int CZ_SPRAY_REQ_INFO = 0xd49; // Size: 26
		public const int CZ_SPRAY_DRAW_INFO = 0xd4a; // Size: 0
		public const int ZC_SPRAY_ID = 0xd4b; // Size: 22
		public const int ZC_SPRAY_DRAW_INFO = 0xd4c; // Size: 0
		public const int ZC_MONSTER_LIFETIME = 0xd4d; // Size: 18
		public const int ZC_SPRAY_LIKE_LIST = 0xd4e; // Size: 0
		public const int ZC_SHARED_MSG = 0xd4f; // Size: 14
		public const int CZ_REQ_TX_ITEM = 0xd50; // Size: 0
		public const int ZC_TEST_DBG = 0xd51; // Size: 0
		public const int ZC_MONSTER_DIST = 0xd52; // Size: 0
		public const int ZC_RESET_SKILL_FORCEID = 0xd53; // Size: 14
		public const int ZC_EMOTICON = 0xd54; // Size: 22
		public const int ZC_SHOW_EMOTICON = 0xd55; // Size: 22
		public const int ZC_TREASUREMARK_BY_MAP = 0xd56; // Size: 0
		public const int ZC_SHOW_LOCAL_MAP = 0xd57; // Size: 0
		public const int ZC_FIX_ANIM = 0xcb6; // Size: 78
		public const int ZC_MOVE_ANIM = 0xcb7; // Size: 16
		public const int CZ_FLEE_OBSTACLE = 0xd58; // Size: 38
		public const int ZC_HOLD_MOVE_PATH = 0xd59; // Size: 15
		public const int ZC_ENTER_HOOK = 0xd5a; // Size: 14
		public const int ZC_LEAVE_HOOK = 0xd5b; // Size: 14
		public const int ZC_GROUND_EFFECT = 0xd5c; // Size: 54
		public const int ZC_FLY = 0xd5d; // Size: 22
		public const int ZC_FLY_MATH = 0xd5f; // Size: 27
		public const int ZC_FLY_OPTION = 0xd5e; // Size: 18
		public const int ZC_FLY_HEIGHT = 0xd60; // Size: 18
		public const int ZC_UPDATE_SHIELD = 0xd61; // Size: 18
		public const int ZC_SHOW_MODEL = 0xd62; // Size: 19
		public const int ZC_SHOW_SCENE_MODEL = 0xd63; // Size: 15
		public const int ZC_SKILL_RANGE_DBG = 0xd64; // Size: 74
		public const int ZC_SKILL_RANGE_FAN = 0xd65; // Size: 50
		public const int ZC_SKILL_RANGE_SQUARE = 0xd66; // Size: 52
		public const int ZC_SKILL_RANGE_CIRCLE = 0xd67; // Size: 40
		public const int ZC_POS_DBG = 0xd68; // Size: 38
		public const int ZC_TEAMID = 0xd69; // Size: 15
		public const int ZC_PC = 0xd6a; // Size: 0
		public const int CZ_LOG = 0xd6b; // Size: 0
		public const int ZC_MOTIONBLUR = 0xd6c; // Size: 15
		public const int ZC_PLAY_FORCE = 0xd6d; // Size: 82
		public const int ZC_CAST_TARGET = 0xd6e; // Size: 18
		public const int ZC_START_INFO = 0xd6f; // Size: 0
		public const int ZC_JOB_EXP_UP = 0xd70; // Size: 26
		public const int ZC_JOB_PTS = 0xd71; // Size: 22
		public const int ZC_MON_STAMINA = 0xd73; // Size: 26
		public const int CZ_CUSTOM_SCP = 0xd74; // Size: 26
		public const int ZC_VIEW_FOCUS = 0xd75; // Size: 28
		public const int ZC_HARDCODED_SKILL = 0xd76; // Size: 30
		public const int CZ_HARDCODED_SKILL = 0xd77; // Size: 46
		public const int ZC_FORCE_MOVE = 0xd78; // Size: 34
		public const int ZC_HSKILL_CONTROL = 0xd79; // Size: 26
		public const int ZC_CANCEL_DEADEVENT = 0xd7a; // Size: 14
		public const int ZC_ACTION_PKS = 0xd7b; // Size: 39
		public const int CZ_HARDCODED_ITEM = 0xd7c; // Size: 34
		public const int CZ_BRIQUET = 0xd7e; // Size: 0
		public const int CZ_CANCEL_TRANSFORM_SKILL = 0xd7d; // Size: 22
		public const int ZC_VIBRATE = 0xd7f; // Size: 34
		public const int ZC_COUNTER_MOVE = 0xd80; // Size: 14
		public const int CZ_COUNTER_ATTACK = 0xd81; // Size: 26
		public const int CZ_CLIENT_DIRECT = 0xd82; // Size: 42
		public const int ZC_CLIENT_DIRECT = 0xd83; // Size: 34
		public const int ZC_OWNER = 0xd84; // Size: 18
		public const int ZC_GD_RANK = 0xd85; // Size: 14
		public const int CZ_RUN_BGEVENT = 0xd86; // Size: 86
		public const int ZC_ADD_SKILL_EFFECT = 0xd87; // Size: 22
		public const int ZC_ITEM_DROPABLE = 0xd88; // Size: 14
		public const int CZ_ITEM_DROP_TO_OBJECT = 0xd89; // Size: 38
		public const int ZC_NORMAL = 0xd8a; // Size: 0
		public const int CZ_G_QUEST_CHECK = 0xd8b; // Size: 26
		public const int ZC_MOVE_PATH_MATH = 0xd8c; // Size: 34
		public const int ZC_SHOW_GROUND_ITEM_MARK = 0xd9d; // Size: 34
		public const int ZC_HELP_LIST = 0xd9e; // Size: 0
		public const int ZC_HELP_ADD = 0xd9f; // Size: 15
		public const int ZC_STD_ANIM = 0xcb8; // Size: 15
		public const int CZ_CLIENT_HIT_LIST = 0xda0; // Size: 0
		public const int ZC_PC_ATKSTATE = 0xda1; // Size: 15
		public const int ZC_SEND_PREMIUM_STATE = 0xda2; // Size: 20
		public const int CZ_HELP_READ_TYPE = 0xda3; // Size: 30
		public const int CZ_MOVE_PATH_END = 0xda4; // Size: 22
		public const int ZC_COLL_DAMAGE = 0xda5; // Size: 15
		public const int CZ_KEYBOARD_BEAT = 0xda6; // Size: 22
		public const int CZ_MOVEHIT_SCP = 0xda7; // Size: 34
		public const int ZC_SYNC_START = 0xda8; // Size: 18
		public const int ZC_SYNC_END = 0xda9; // Size: 18
		public const int ZC_SYNC_EXEC = 0xdaa; // Size: 14
		public const int ZC_SYNC_EXEC_BY_SKILL_TIME = 0xdab; // Size: 22
		public const int CZ_STOP_TIMEACTION = 0xdac; // Size: 23
		public const int CZ_REQ_DUMMYPC_INFO = 0xdad; // Size: 30
		public const int CZ_VISIT_BARRACK = 0xdae; // Size: 86
		public const int CZ_SPC_SKILL_POS = 0xdaf; // Size: 34
		public const int CZ_REQ_MINITEXT = 0xdb3; // Size: 278
		public const int ZC_PC_MOVE_STOP = 0xdb4; // Size: 52
		public const int CZ_SKILL_TOOL_GROUND_POS = 0xdbe; // Size: 39
		public const int CZ_CHANGE_HEAD = 0xdb0; // Size: 86
		public const int CZ_CREATE_ARROW_CRAFT = 0xdb1; // Size: 26
		public const int CZ_EXCHANGE_ANTIQUE = 0xdb2; // Size: 34
		public const int CZ_REQ_GM_ORDER = 0xe27; // Size: 214
		public const int CZ_REPORT_AUTOBOT = 0xe29; // Size: 86
		public const int CZ_REPORT_PVP_ZOOM = 0xe2a; // Size: 22
		public const int CZ_SCREENSHOT_HASH = 0xe40; // Size: 55
		public const int CZ_REQ_MOVE_TO_INDUN = 0xe41; // Size: 30
		public const int CZ_CLEAR_INDUN_REG = 0xe42; // Size: 22
		public const int CZ_REQ_REGISTER_TO_INDUN = 0xe43; // Size: 26
		public const int CZ_REQ_GUILD_MEMBER_AUTHORITY = 0xe44; // Size: 35
		public const int CZ_TPSHOP_RTPP_FOR_TEST = 0xe45; // Size: 22
		public const int CZ_REQ_UNDERSTAFF_ENTER_ALLOW = 0xe47; // Size: 22
		public const int CZ_REQ_UNDERSTAFF_ENTER_ALLOW_WITH_PARTY = 0xe48; // Size: 26
		public const int ZC_PLAY_PAIR_ANIMATION = 0xe4a; // Size: 340
		public const int ZC_PLAY_ATTACH_MODEL_ANIM = 0xe4d; // Size: 26
		public const int ZC_FISHING_ITEM_LIST = 0xe53; // Size: 0
		public const int ZC_ADVENTURE_BOOK_INFO = 0xe57; // Size: 0
		public const int ZC_CANCEL_MOUSE_MOVE = 0xe5e; // Size: 14
		public const int ZC_COLONY_OCCUPATION_INFO = 0xe6c; // Size: 0
		public const int ZC_BROAD_CAST_MY_INFO = 0xe5f; // Size: 31
		public const int CZ_REQ_RETURN_TO_CITY_FROM_COLONY_WAR = 0xe6d; // Size: 22
		public const int ZC_ATTENDANCE_RECEIPT_REWARD = 0xe66; // Size: 0
		public const int CZ_ATTENDANCE_REWARD_CLICK = 0xe67; // Size: 26
		public const int ZC_ATTENDANCE_REWARD_CHECK_UI_ON = 0xe68; // Size: 12
		public const int ZC_ERROR_INFO = 0xeb0; // Size: 0
		public const int ZC_RESERVE_PROPERTY = 0xee3; // Size: 0
		public const int ZC_REDIS_RANKING_INFO = 0xee9; // Size: 0
		public const int CZ_REQUEST_COLONYWAR_ENDTIME = 0xe6e; // Size: 22
		public const int ZC_RESPONSE_COLONYWAR_ENDTIME = 0xe6f; // Size: 26
		public const int ZC_ALTER_HIT_RADIUS = 0xeed; // Size: 22
		public const int ZC_SET_COLONY_TIME_CHEAT_FAIL = 0xe72; // Size: 16
		public const int ZC_SET_COLONY_TIME_CHEAT_SUCCESS = 0xe73; // Size: 16
		public const int ZC_GUILD_BUILDING_OBJECT_ADD = 0xef3; // Size: 0
		public const int ZC_GUILD_BUILDING_OBJECT_REMOVE = 0xef4; // Size: 0
		public const int ZC_START_IMITATING_ANIMATION = 0xf02; // Size: 18
		public const int ZC_STOP_IMITATING_ANIMATION = 0xf03; // Size: 14
		public const int CZ_START_IMITATING_ANIMATION_ACK = 0xf04; // Size: 22
		public const int CZ_FOLLOW_TO_ACTOR_ACK = 0xf05; // Size: 22
		public const int ZC_COLONY_TAX_TOTAL_AMOUNT = 0xe74; // Size: 50
		public const int ZC_COLONY_TAX_RATE_LIST = 0xe75; // Size: 0
		public const int ZC_COLONY_TAX_LORD_READY = 0xe76; // Size: 153
		public const int ZC_COLONY_TAX_LORD_START = 0xe77; // Size: 38
		public const int ZC_COLONY_TAX_LORD_END = 0xe78; // Size: 14
		public const int ZC_COLONY_TAX_RATE_SET = 0xe79; // Size: 42
		public const int ZC_COLONY_TAX_CHEQUE_LIST = 0xe7b; // Size: 0
		public const int CZ_COLONY_TAX_RATE_REQ_SET = 0xe7a; // Size: 30
		public const int CZ_COLONY_TAX_CHEQUE_REQ_LIST = 0xe7c; // Size: 22
		public const int CZ_COLONY_TAX_CHEQUE_REQ_SEND = 0xe7d; // Size: 0
		public const int CZ_COLONY_TAX_HISTORY_REQ_LIST = 0xe7e; // Size: 22
		public const int ZC_COLONY_TAX_HISTORY_LIST = 0xe7f; // Size: 0
		public const int ZC_COLONY_TAX_PAYMENT_LIST = 0xe80; // Size: 0
		public const int CZ_COLONY_TAX_PAYMENT_REQ_RECV = 0xe81; // Size: 30
		public const int CZ_COLONY_TAX_PAYMENT_REQ_LIST = 0xe82; // Size: 22
		public const int CZ_REQUEST_RVR_ENDTIME = 0xe83; // Size: 22
		public const int ZC_RESPONSE_RVR_ENDTIME = 0xe84; // Size: 26
		public const int CZ_REGISTER_NEW_GUILD_EMBLEM = 0xe85; // Size: 20107
		public const int CZ_CHANGE_GUILD_EMBLEM = 0xe86; // Size: 20108
		public const int ZC_UPDATE_GUILD_EMBLEM = 0xe87; // Size: 24
		public const int CZ_REQUEST_CERTAIN_GUILD_EMBLEM = 0xe88; // Size: 32
		public const int ZC_RESPONSE_CERTAIN_GUILD_EMBLEM = 0xe89; // Size: 20040
		public const int CZ_REQUEST_GUILD_EMBLEM_INFO = 0xe8a; // Size: 32
		public const int ZC_RESPONSE_GUILD_EMBLEM_INFO = 0xe8b; // Size: 102
		public const int CZ_REQUEST_GUILD_INDEX = 0xe8c; // Size: 30
		public const int ZC_RESPONSE_GUILD_INDEX = 0xe8d; // Size: 24
		public const int CZ_REPORT_GUILDEMBLEM = 0xe8e; // Size: 86
		public const int ZC_DELETE_GUILD_EMBLEM = 0xe8f; // Size: 24
		public const int CZ_DELETE_GUILD_EMBLEM = 0xe90; // Size: 22
		public const int ZC_ADDITIONAL_SKILL_POINT = 0xd72; // Size: 0
		public const int ZC_START_FIELDBOSS_WORLD_EVENT = 0xf1b; // Size: 0
		public const int ZC_END_FIELDBOSS_WORLD_EVENT = 0xf1c; // Size: 16
		public const int ZC_FIELDBOSS_REMOVE_ITEM = 0xf1d; // Size: 14
		public const int CZ_BID_FIELDBOSS_WORLD_EVENT = 0xf1e; // Size: 22
		public const int ZC_WIN_FIELDBOSS_WORLD_EVENT_ITEM = 0xf1f; // Size: 14
		public const int ZC_LOSE_FIELDBOSS_WORLD_EVENT_ITEM = 0xf20; // Size: 14
		public const int ZC_START_CASUAL_GAMBLE = 0xf3a; // Size: 0
		public const int ZC_CASUAL_GAMBLE_ITEM_GET = 0xf3b; // Size: 18
		public const int CZ_REQUEST_CASUAL_GAMBLE = 0xf3c; // Size: 22
		public const int ZC_END_CASUAL_GAMBLE = 0xf3d; // Size: 16
		public const int ZC_NXA_REQ_TICKET = 0xe91; // Size: 16
		public const int CZ_NXA_TICKET = 0xe92; // Size: 1046
		public const int CZ_NXA_REQ_BALANCE = 0xe93; // Size: 22
		public const int ZC_NXA_BALANCE = 0xe94; // Size: 40
		public const int CZ_NXA_REQ_ITEMLIST = 0xe95; // Size: 23
		public const int ZC_NXA_ITEMLIST = 0xe96; // Size: 0
		public const int CZ_NXA_REQ_PURCHASE = 0xe97; // Size: 27
		public const int ZC_NXA_PURCHASE = 0xe98; // Size: 4106
		public const int CZ_NXA_REQ_PICKUP_READY_ITEMS = 0xe99; // Size: 2071
		public const int CZ_NXA_REQ_PURCHASE_CANCEL = 0xe9a; // Size: 22
		public const int ZC_NXA_SELLITEMLIST = 0xe9b; // Size: 0
		public const int ZC_CASH_INVENTORY_LIST = 0xeee; // Size: 0
		public const int CZ_NEXON_PAYMENT_PAGE = 0xeef; // Size: 22
		public const int ZC_NEXON_PAYMENT_PAGE = 0xef0; // Size: 522
		public const int ZC_ADD_CHATBALLOON_SKIN = 0xf76; // Size: 0
		public const int CZ_SET_CHATBALLOON_SKIN = 0xf77; // Size: 26
		public const int ZC_SET_CHATBALLOON_SKIN = 0xf78; // Size: 34
		public const int ZC_UPDATE_CHATBALLOON_SKIN = 0xf79; // Size: 16
		public const int CZ_DO_CLIENT_MOVE_CHECK = 0xf7a; // Size: 22
		public const int ZC_IS_SUMMONING_MONSTER = 0xf7b; // Size: 15
		public const int CZ_MYPAGE_COMMENT_ADD = 0xd8d; // Size: 290
		public const int CZ_MYPAGE_COMMENT_DELETE = 0xd8e; // Size: 30
		public const int CZ_GET_TARGET_MYPAGE = 0xd90; // Size: 26
		public const int CZ_ON_MYPAGE_MODE = 0xd91; // Size: 26
		public const int CZ_RESET_SOCIAL_MODE = 0xd92; // Size: 22
		public const int CZ_GUESTPAGE_COMMENT_ADD = 0xd8f; // Size: 290
		public const int CZ_GET_TARGET_GUESTPAGE = 0xd93; // Size: 26
		public const int CZ_ADD_SELLMODE_ITEM = 0xd94; // Size: 42
		public const int CZ_DELETE_SELLMODE_ITEM = 0xd95; // Size: 30
		public const int CZ_ON_SELLITEM_MODE = 0xd96; // Size: 26
		public const int CZ_ON_ITEMBUY_MODE = 0xd9b; // Size: 0
		public const int ZC_MYPAGE_MAP = 0xd97; // Size: 0
		public const int ZC_GUESTPAGE_MAP = 0xd98; // Size: 0
		public const int ZC_ON_MYPAGE_MODE = 0xd99; // Size: 0
		public const int ZC_RESET_SOCIAL_MODE = 0xd9a; // Size: 14
		public const int ZC_ON_BUYITEM_MODE = 0xd9c; // Size: 0
		public const int CZ_STOP_ALLPC = 0xdb5; // Size: 22
		public const int CZ_COMPLETE_PRELOAD = 0xdb6; // Size: 26
		public const int CZ_MGAME_JOIN_CMD = 0xdb7; // Size: 58
		public const int ZC_ATTACH_TO_OBJ = 0xdb9; // Size: 53
		public const int ZC_DETACH_FROM_OBJ = 0xdba; // Size: 18
		public const int ZC_RUN_FROM = 0xdbb; // Size: 18
		public const int ZC_LOOKAT_OBJ = 0xdbc; // Size: 18
		public const int CZ_SKILL_CELL_LIST = 0xdbd; // Size: 0
		public const int CZ_DIRECTION_PROCESS = 0xdbf; // Size: 34
		public const int CZ_DIRECTION_MOVE_STATE = 0xdc0; // Size: 0
		public const int ZC_TO_ALL_CLIENT = 0xdc1; // Size: 0
		public const int ZC_TO_CLIENT = 0xdc2; // Size: 0
		public const int CZ_REWARD_CMD = 0xdc3; // Size: 26
		public const int CZ_PROPERTY_COMPARE = 0xdc4; // Size: 28
		public const int ZC_PROPERTY_COMPARE = 0xdc5; // Size: 0
		public const int ZC_PROPERTY_COMPARE_FOR_ACT = 0xdc6; // Size: 0
		public const int ZC_SEND_CASH_VALUE = 0xdc9; // Size: 0
		public const int ZC_FACTION = 0xdc8; // Size: 18
		public const int ZC_BEGIN_KILL_LOG = 0xdca; // Size: 16
		public const int ZC_END_KILL_LOG = 0xdcb; // Size: 16
		public const int ZC_CLEAR_KILL_LOG = 0xdcc; // Size: 16
		public const int CZ_NPC_AUCTION_CMD = 0xdcd; // Size: 42
		public const int ZC_DIRECTION_APC = 0xdce; // Size: 30
		public const int ZC_BGMODEL_ANIM_INFO = 0xdcf; // Size: 19
		public const int ZC_ATTACH_BY_KNOCKBACK = 0xdd0; // Size: 42
		public const int CZ_OBJECT_MOVE = 0xdd1; // Size: 42
		public const int CZ_CONTROL_OBJECT_ROTATE = 0xdd2; // Size: 34
		public const int CZ_SUMMON_COMMAND = 0xdd3; // Size: 30
		public const int CZ_VEHICLE_RIDE = 0xdd4; // Size: 27
		public const int CZ_REQ_ACHIEVE_RANK_PAGE_INFO = 0xdd5; // Size: 90
		public const int ZC_SPC_TRIGGER_EXEC = 0xdd6; // Size: 34
		public const int CZ_REQ_MGAME_VIEW = 0xdd7; // Size: 30
		public const int CZ_REQ_MGAME_CHAT = 0xdd8; // Size: 0
		public const int CZ_TOURNAMENT_GIFT = 0xdd9; // Size: 30
		public const int CZ_PARTY_INVITE_ACCEPT = 0xdda; // Size: 153
		public const int CZ_PARTY_INVITE_CANCEL = 0xddb; // Size: 103
		public const int CZ_PARTY_PROP_CHANGE = 0xddc; // Size: 159
		public const int CZ_REQ_MARKET_REGISTER = 0xddd; // Size: 56
		public const int CZ_REQ_MARKET_MINMAX_INFO = 0xdde; // Size: 30
		public const int CZ_REQ_MARKET_BUY = 0xddf; // Size: 0
		public const int CZ_REQ_CABINET_LIST = 0xde0; // Size: 22
		public const int CZ_REQ_GET_CABINET_ITEM = 0xde1; // Size: 38
		public const int CZ_REQ_CANCEL_MARKET_ITEM = 0xde2; // Size: 30
		public const int CZ_OBJ_RECORD_POS = 0xde4; // Size: 0
		public const int CZ_FORMATION_CMD = 0xde5; // Size: 44
		public const int CZ_REGISTER_AUTOSELLER = 0xde6; // Size: 0
		public const int CZ_INV_ITEM_LOCK = 0xde3; // Size: 31
		public const int CZ_OPEN_AUTOSELLER = 0xde7; // Size: 94
		public const int CZ_BUY_AUTOSELLER_ITEMS = 0xde8; // Size: 0
		public const int CZ_SELL_MY_AUTOSELLER_ITEMS = 0xde9; // Size: 0
		public const int CZ_PUZZLE_CRAFT = 0xdea; // Size: 0
		public const int CZ_PET_EQUIP = 0xdeb; // Size: 46
		public const int CZ_PET_AUTO_ATK = 0xdec; // Size: 23
		public const int ZC_PET_AUTO_ATK = 0xded; // Size: 23
		public const int ZC_TO_SOMEWHERE_CLIENT = 0xdee; // Size: 0
		public const int CZ_REVEAL_NPC_STATE = 0xdef; // Size: 26
		public const int CZ_CHANGE_CHANNEL = 0xdf0; // Size: 24
		public const int CZ_REQ_CHANNEL_TRAFFICS = 0xdf1; // Size: 24
		public const int CZ_BUY_PROPERTYSHOP_ITEM = 0xdf2; // Size: 0
		public const int CZ_SKILL_USE_HEIGHT = 0xdf3; // Size: 26
		public const int CZ_CHANGE_GUILD_NEUTRALITY = 0xdf4; // Size: 22
		public const int CZ_SAVE_GUILD_BOARD = 0xdf5; // Size: 122
		public const int CZ_DELETE_PARTY_EVENT = 0xdf6; // Size: 32
		public const int CZ_PING = 0xdf7; // Size: 22
		public const int ZC_PING = 0xdf8; // Size: 22
		public const int CZ_REQ_REMAIN_NEXONCASH = 0xdf9; // Size: 22
		public const int CZ_REQ_OPEN_INGAMESHOP_UI = 0xdfa; // Size: 22
		public const int CZ_REQ_BUY_INGAMESHOP_ITEM = 0xdfb; // Size: 90
		public const int CZ_REQ_BUY_ALL_INGAMESHOP_ITEM = 0xdfc; // Size: 22
		public const int CZ_REQ_PICKUP_CASHITEM = 0xdfd; // Size: 49
		public const int CZ_REQ_REFUND_CASHITEM = 0xdfe; // Size: 45
		public const int ZC_XIGNCODE_BUFFER = 0xdff; // Size: 536
		public const int CZ_XIGNCODE_BUFFER = 0xe00; // Size: 536
		public const int CZ_SYSTEM_LOG_SAVE_TO_MONGODB = 0xe01; // Size: 292
		public const int CZ_CHANGE_TITLE = 0xe02; // Size: 86
		public const int CZ_PC_COMMENT_CHANGE = 0xe03; // Size: 0
		public const int CZ_AUTTOSELLER_BUYER_CLOSE = 0xe04; // Size: 30
		public const int CZ_REQ_ITEM_LIST = 0xe05; // Size: 23
		public const int CZ_REQ_ACC_WARE_VIS_LOG = 0xe06; // Size: 22
		public const int CZ_HIT_MISSILE = 0xe07; // Size: 26
		public const int CZ_PARTY_JOIN_BY_LINK = 0xe08; // Size: 39
		public const int CZ_PVP_ZONE_CMD = 0xe09; // Size: 38
		public const int CZ_PVP_CHAT = 0xe0a; // Size: 0
		public const int CZ_CARDBATTLE_CMD = 0xe0b; // Size: 38
		public const int CZ_REQ_UPDATE_CONTENTS_SESSION = 0xe0c; // Size: 22
		public const int CZ_REQ_FRIENDLY_FIGHT = 0xe0d; // Size: 27
		public const int CZ_HARDSKILL_POS_LIST = 0xe0e; // Size: 0
		public const int CZ_CART_POSITION = 0xe0f; // Size: 38
		public const int CZ_REQ_RIDE_CART = 0xe10; // Size: 30
		public const int CZ_DUMMYPC_SKILL_POS = 0xe11; // Size: 38
		public const int CZ_PARTY_MEMBER_SKILL_USE = 0xe14; // Size: 0
		public const int CZ_PARTY_MEMBER_SKILL_ACCEPT = 0xe15; // Size: 35
		public const int CZ_UDP_RTT_CHECK = 0xe21; // Size: 26
		public const int ZC_UDP_RTT_CHECK = 0xe22; // Size: 18
		public const int CZ_UDP_RTT_CHECK_ACK = 0xe23; // Size: 30
		public const int CZ_HEARTBEAT = 0xe24; // Size: 26
		public const int CZ_PARTY_INVENTORY_LOAD = 0xe2b; // Size: 24
		public const int CZ_REQ_MOVE_PARTYINV_TO_ACCOUNT = 0xe2d; // Size: 0
		public const int CZ_PVP_COMMAND = 0xe2e; // Size: 35
		public const int CZ_REQ_CancelGachaCube = 0xe2f; // Size: 22
		public const int CZ_WAREHOUSE_TAKE_LIST = 0xe30; // Size: 0
		public const int CZ_SAVE_AUTO_MACRO = 0xe31; // Size: 0
		public const int CZ_REQUEST_LOAD_ITEM_BUY_LIMIT = 0xe32; // Size: 22
		public const int CZ_AUTO_STATE = 0xe33; // Size: 23
		public const int CZ_FIXED_NOTICE_SHOW = 0xe35; // Size: 22
		public const int CZ_SAGE_SKILL_GO_FRIEND = 0xe36; // Size: 102
		public const int CZ_RUN_GAMEEXIT_TIMER = 0xe34; // Size: 86
		public const int CZ_REQUEST_CHANGE_NAME = 0xe37; // Size: 78
		public const int CZ_REQUEST_CHANGE_PET_NAME = 0xe38; // Size: 94
		public const int ZC_HOLD_EXP_BOOK_TIME = 0xe3d; // Size: 37
		public const int CZ_HOLD_EXP_BOOK_TIME = 0xe3e; // Size: 26
		public const int ZC_BUFF_UPDATE_TIME = 0xe3f; // Size: 34
		public const int CZ_CYOU_CTU_CLIENT_MSG = 0xe3a; // Size: 1054
		public const int CZ_RUN_FUNCTION_DUMP = 0xe4e; // Size: 0
		public const int ZC_RUN_FUNCTION_DUMP = 0xe4f; // Size: 0
		public const int ZC_RUN_FUNCTION_DUMP_ERROR = 0xe50; // Size: 0
		public const int ZC_RUN_FUNCTION_DUMP_PRINT = 0xe51; // Size: 0
		public const int ZC_ATTACH_TO_SLOT = 0xe52; // Size: 26
		public const int CZ_REQ_GUILD_NEUTRALITY_ALARM = 0xe5b; // Size: 26
		public const int CZ_SYNC_POS = 0xe56; // Size: 38
		public const int CZ_DISCONNECT_REASON_FOR_LOG = 0xe58; // Size: 0
		public const int CZ_LOAD_COMPLETE = 0xe60; // Size: 22
		public const int ZC_LOAD_COMPLETE = 0xe61; // Size: 16
		public const int CZ_ACCEPT_CHALLENGE_MODE = 0xe62; // Size: 26
		public const int CZ_ACCEPT_CHALLENGE_MODE_BY_PCBANG = 0xeba; // Size: 26
		public const int CZ_ACCEPT_NEXT_LEVEL_CHALLENGE_MODE = 0xe63; // Size: 26
		public const int CZ_ACCEPT_STOP_LEVEL_CHALLENGE_MODE = 0xe64; // Size: 26
		public const int ZC_UPDATE_CHALLENGE_MODE_WARP_PORTAL_MARK = 0xe65; // Size: 23
		public const int ZC_CYOU_KICK_USER_EXIT_CLIENT = 0xe3c; // Size: 16
		public const int CZ_REQ_PARTY_INFO = 0xe9c; // Size: 22
		public const int CZ_BADPLAYER_REPORT = 0xeaf; // Size: 158
		public const int CZ_REQ_RETURN_ORIGIN_SERVER = 0xe9d; // Size: 22
		public const int CZ_ANS_GIVEUP_PREV_PLAYING_INDUN = 0xe9e; // Size: 23
		public const int ZC_SEND_JSON_DUMP = 0xeb1; // Size: 0
		public const int CZ_SEND_JSON_DUMP = 0xeb2; // Size: 0
		public const int CZ_CLIENT_REMOTE_LOG = 0xeb3; // Size: 2584
		public const int ZC_FOLLOW_TO_ACTOR = 0xe9f; // Size: 39
		public const int ZC_STOP_FOLLOW_TO_ACTOR = 0xea0; // Size: 14
		public const int ZC_FIXCAMERA = 0xebb; // Size: 26
		public const int ZC_CANCEL_FIXCAMERA = 0xebc; // Size: 16
		public const int CZ_REQ_PCBANG_SHOP_UI = 0xebf; // Size: 26
		public const int CZ_REQ_PCBANG_SHOP_CONNECT_REWARD = 0xec0; // Size: 86
		public const int CZ_REQ_PCBANG_SHOP_TOTAL_REWARD = 0xec1; // Size: 26
		public const int CZ_REQ_PCBANG_SHOP_PURCHASE = 0xec2; // Size: 26
		public const int CZ_REQ_PCBANG_SHOP_RENTAL = 0xec3; // Size: 26
		public const int CZ_REQ_PCBANG_SHOP_REFRESH = 0xec4; // Size: 22
		public const int ZC_PCBANG_SHOP_COMMON = 0xec5; // Size: 66
		public const int ZC_PCBANG_SHOP_MAIN = 0xec6; // Size: 0
		public const int ZC_PCBANG_SHOP_POINTSHOP_CATALOG = 0xec7; // Size: 0
		public const int ZC_PCBANG_SHOP_POINTSHOP_BUY_COUNT = 0xec8; // Size: 0
		public const int ZC_PCBANG_SHOP_RENTAL = 0xec9; // Size: 0
		public const int ZC_PCBANG_SHOP_GUIDE = 0xeca; // Size: 0
		public const int ZC_PCBANG_SHOP_REWARD = 0xecb; // Size: 0
		public const int ZC_PCBANG_STATE = 0xecc; // Size: 15
		public const int ZC_PCBANG_POINT = 0xecd; // Size: 22
		public const int ZC_SET_WEBSERVICE_URL = 0xea1; // Size: 266
		public const int CZ_CREATE_GUILD_BY_WEB = 0xea2; // Size: 71
		public const int CZ_GUILD_MEMBER_INVITE_BY_WEB = 0xea3; // Size: 95
		public const int ZC_GUILD_MEMBER_INVITE_BY_WEB = 0xea4; // Size: 91
		public const int CZ_WEEKLY_BOSS_INDUN_ENTER = 0xea5; // Size: 23
		public const int CZ_GUILD_MEMBER_INVITE_ACCEPT_BY_WEB = 0xea6; // Size: 102
		public const int CZ_GUILD_APPLICATION_USER_ACCEPT = 0xea7; // Size: 95
		public const int ZC_DECREASE_SILVER = 0xea8; // Size: 14
		public const int CZ_POST_GUILD_EMBLEM = 0xea9; // Size: 20026
		public const int CZ_REQUEST_CERTAIN_WEBSERVICE_URL = 0xeaa; // Size: 24
		public const int ZC_RESPONSE_CERTAIN_WEBSERVICE_URL = 0xeab; // Size: 268
		public const int CZ_GUILD_AGIT_ENTER = 0xeac; // Size: 159
		public const int ZC_SOLD_ITEM_NOTICE = 0xef1; // Size: 158
		public const int ZC_RELOAD_SELL_LIST = 0xead; // Size: 16
		public const int ZC_NOTICE_BROKEN_SYNC_MARKET_ITEM = 0xeae; // Size: 18
		public const int CZ_SWAP_ITEM_IN_WAREHOUSE = 0xebd; // Size: 46
		public const int ZC_SWAP_ITEM_IN_WAREHOUSE_FAIL = 0xebe; // Size: 18
		public const int CZ_SEND_BEAUTYSHOP_PURCHASE_LIST = 0xece; // Size: 0
		public const int ZC_RES_BEAUTYSHOP_PURCHASED_HAIR_LIST = 0xed0; // Size: 0
		public const int CZ_REQ_BEAUTYSHOP_INFO = 0xecf; // Size: 23
		public const int CZ_SEND_BEAUTYSHOP_TRYITON_LIST = 0xed1; // Size: 0
		public const int CZ_SEND_BEAUTYSHOP_TRYITON_CANCEL = 0xed2; // Size: 22
		public const int ZC_VERTICAL_MOTION = 0xedb; // Size: 23
		public const int CZ_REQ_PLAY_FLUTING = 0xedc; // Size: 31
		public const int ZC_PLAY_FLUTING = 0xedd; // Size: 24
		public const int CZ_REQ_READY_FLUTING = 0xede; // Size: 23
		public const int ZC_READY_FLUTING = 0xedf; // Size: 15
		public const int CZ_REQ_STOP_FLUTING = 0xee0; // Size: 31
		public const int ZC_STOP_FLUTING = 0xee1; // Size: 23
		public const int ZC_STOP_FLUTING_ALL = 0xee2; // Size: 14
		public const int CZ_REQ_SOLO_DUNGEON_REWARD = 0xee4; // Size: 22
		public const int CZ_REQ_SOLO_DUNGEON_RANKING_PAGE = 0xee5; // Size: 22
		public const int ZC_SOLO_DUNGEON_STAGE_SCORE = 0xee6; // Size: 34
		public const int ZC_SOLO_DUNGEON_RANKING = 0xee7; // Size: 0
		public const int ZC_SOLO_DUNGEON_MY_RANKING = 0xee8; // Size: 0
		public const int ZC_CUSTOM_WHEEL_ZOOM = 0xeea; // Size: 23
		public const int ZC_MGAME_POSITION = 0xeeb; // Size: 0
		public const int ZC_ITEM_LOCK_STATE = 0xeec; // Size: 19
		public const int ZC_SEND_COLONY_MARKET_FEE_PAYMENT_LIST = 0xe70; // Size: 0
		public const int CZ_REQ_COLONY_MARKET_FEE_PAYMENT = 0xe71; // Size: 42
		public const int CZ_REQ_GUILD_ASSET = 0xef2; // Size: 22
		public const int CZ_CHANGE_REPRESENTATION_CLASS = 0xef5; // Size: 26
		public const int ZC_PROPERTY_COMPARE_FOR_REP_CLASS = 0xdc7; // Size: 0
		public const int ZC_UPDATE_REPRESENTATION_CLASS = 0xce0; // Size: 22
		public const int CZ_REQ_COMMANDER_INFO = 0xef6; // Size: 24
		public const int ZC_CUSTOM_COMMANDER_INFO = 0xef7; // Size: 32
		public const int ZC_TRUST_INFO = 0xef8; // Size: 62
		public const int ZC_GUILD_COOLDOWN_LIST = 0xef9; // Size: 0
		public const int CZ_REQUEST_CHARACTER_INDUN_INFO = 0xefa; // Size: 22
		public const int ZC_CLASS_RESET_POINT_INFO = 0xefb; // Size: 18
		public const int ZC_EQUIP_CARD_INFO = 0xefc; // Size: 0
		public const int ZC_EQUIP_GEM_INFO = 0xefd; // Size: 0
		public const int ZC_FADE_IN = 0xefe; // Size: 14
		public const int CZ_REQ_LEARN_ABILITY = 0xf00; // Size: 0
		public const int CZ_REQUEST_EVENT_USER_TYPE_INFO = 0xf06; // Size: 22
		public const int CZ_REQUEST_USED_MEDAL_TOTAL = 0xf07; // Size: 22
		public const int CZ_DPK_QUEST_DESTORY_SESSIONOBJ = 0xf0d; // Size: 286
		public const int ZC_ZOMBIE_ALIVE = 0xf08; // Size: 16
		public const int CZ_ZOMBIE_ALIVE_ACK = 0xf09; // Size: 22
		public const int ZC_FRIENDLY_STATE = 0xf0a; // Size: 11
		public const int ZC_CHANGE_SKIN_COLOR = 0xf0b; // Size: 18
		public const int ZC_WEEKLY_BOSS_RANK_INFO = 0xf21; // Size: 0
		public const int ZC_WEEKLY_BOSS_RANK_MY_DAMAGE = 0xf22; // Size: 22
		public const int ZC_WEEKLY_BOSS_ACCUMULATED_DAMAGE = 0xf23; // Size: 22
		public const int ZC_WEEKLY_BOSS_ABSOLUTE_REWARD_LIST = 0xf24; // Size: 0
		public const int ZC_WEEKLY_BOSS_RECEIVED_ABSOLUTE_REWARD_LIST = 0xf25; // Size: 0
		public const int ZC_WEEKLY_BOSS_RANKING_REWARD_LIST = 0xf29; // Size: 0
		public const int ZC_WEEKLY_BOSS_RECEIVED_RANKING_REWARD = 0xf28; // Size: 18
		public const int CZ_REQUEST_WEEKLY_BOSS_ABSOLUTE_REWARD_LIST = 0xf26; // Size: 26
		public const int CZ_REQUEST_WEEKLY_BOSS_RANKING_REWARD_LIST = 0xf2a; // Size: 26
		public const int CZ_REQUEST_WEEKLY_BOSS_RECEIVE_RANKING_REWARD = 0xf2b; // Size: 26
		public const int CZ_REQUEST_WEEKLY_BOSS_RECEIVE_ABSOLUTE_REWARD = 0xf27; // Size: 26
		public const int CZ_REQUEST_WEEKLY_BOSS_ACCEPT_ABSOLUTE_REWARD = 0xf2c; // Size: 34
		public const int CZ_REQUEST_WEEKLY_BOSS_ACCEPT_ABSOLUTE_REWARD_ALL = 0xf2d; // Size: 26
		public const int CZ_REQUEST_WEEKLY_BOSS_ACCEPT_RANKING_REWARD = 0xf2e; // Size: 30
		public const int CZ_REQUEST_WEEKLY_BOSS_RANKING_INFO_LIST = 0xf2f; // Size: 28
		public const int CZ_REQUEST_WEEKLY_BOSS_NOW_WEEK_NUM = 0xf30; // Size: 22
		public const int CZ_REQUEST_WEEKLY_BOSS_START_TIME = 0xf31; // Size: 26
		public const int CZ_REQUEST_WEEKLY_BOSS_END_TIME = 0xf32; // Size: 26
		public const int CZ_REQUEST_WEEKLY_BOSS_PATTERN_INFO = 0xf33; // Size: 26
		public const int ZC_WEEKLY_BOSS_NOW_WEEK_NUM = 0xf34; // Size: 14
		public const int ZC_WEEKLY_BOSS_START_TIME = 0xf35; // Size: 26
		public const int ZC_WEEKLY_BOSS_END_TIME = 0xf36; // Size: 26
		public const int ZC_WEEKLY_BOSS_PATTERN_INFO = 0xf37; // Size: 0
		public const int CZ_REQUEST_DPS_START = 0xf38; // Size: 22
		public const int ZC_REQUEST_DPS_START = 0xf39; // Size: 26
		public const int ZC_CONFUSE_STATE = 0xf13; // Size: 15
		public const int ZC_ADDONUI_MSG = 0xf14; // Size: 0
		public const int CZ_COLONY_REWARD_REQ = 0xf15; // Size: 51
		public const int ZC_COLONY_REWARD_DETAILLIST_UPDATE = 0xf16; // Size: 22
		public const int ZC_COLONY_SECONDLEAGUE_REWARD_START = 0xf17; // Size: 38
		public const int ZC_COLONY_SECONDLEAGUE_REWARD_END = 0xf18; // Size: 38
		public const int CZ_COLONY_TAXINQUIRELIST_REQ = 0xf19; // Size: 22
		public const int ZC_COLONY_TAXINQUIRELIST_REQ = 0xf1a; // Size: 0
		public const int ZC_REBUILD_POPUP = 0xf63; // Size: 16
		public const int CZ_FORCE_SKILL_RANGE = 0xf6c; // Size: 54
		public const int CZ_CANCEL_PAIR_ANIMATION = 0xf6e; // Size: 22
		public const int ZC_SET_DAYLIGHT_INFO = 0xf6f; // Size: 0
		public const int ZC_DAYLIGHT_SYNCHRONIZE_TIME = 0xf70; // Size: 14
		public const int ZC_DAYLIGHT_FIXED = 0xf71; // Size: 35
		public const int CZ_VARIABLE_RANGE_RESULT = 0xf6d; // Size: 38
		public const int CZ_UDP_MOVE_INFO = 0xf73; // Size: 65
		public const int ZC_UDP_MOVE_INFO = 0xf74; // Size: 80
		public const int ZC_MAIN_SECTOR_INFO = 0xf75; // Size: 0
		public const int CZ_ACCEPT_FIELD_DUNGEON_REJOIN = 0xf72; // Size: 22


		private static readonly Dictionary<int, int> _sizes = new Dictionary<int, int>();
		private static readonly Dictionary<int, string> _names = new Dictionary<int, string>();

		static Op()
		{
			_sizes[CB_LOGIN] = 4477;
			_sizes[CB_LOGIN_BY_PASSPORT] = 1174;
			_sizes[CB_LOGOUT] = 22;
			_sizes[CB_START_GAME] = 25;
			_sizes[CB_START_BARRACK] = 23;
			_sizes[CB_COMMANDER_CREATE] = 113;
			_sizes[CB_COMMANDER_DESTROY] = 30;
			_sizes[CB_CHECK_CLIENT_INTEGRITY] = 86;
			_sizes[CB_CLIENT_INTEGRITY_FAIL] = 1047;
			_sizes[CB_NOT_AUTHORIZED_ADDON_LIST] = 1051;
			_sizes[CB_ECHO] = 42;
			_sizes[CB_BARRACKNAME_CHANGE] = 86;
			_sizes[CB_COMMANDER_MOVE] = 43;
			_sizes[CB_COMPANION_MOVE] = 50;
			_sizes[CB_CHECK_MARKET_REGISTERED] = 30;
			_sizes[BC_LOGINOK] = 156;
			_sizes[BC_CYOU_LOGIN_FAIL] = 16;
			_sizes[BC_LOGIN_PACKET_RECEIVED] = 16;
			_sizes[BC_LOGOUTOK] = 16;
			_sizes[BC_START_GAMEOK] = 37;
			_sizes[BC_SINGLE_INFO] = 385;
			_sizes[BC_COMMANDER_LIST] = 0;
			_sizes[BC_COMMANDER_CREATE_SLOTID] = 11;
			_sizes[BC_COMMANDER_CREATE] = 530;
			_sizes[BC_COMMANDER_DESTROY] = 11;
			_sizes[BC_MESSAGE] = 0;
			_sizes[BC_ECHO] = 30;
			_sizes[BC_IES_MODIFY_INFO] = 0;
			_sizes[BC_IES_MODIFY_LIST] = 0;
			_sizes[CB_IES_REVISION_DELETE] = 0;
			_sizes[BC_IES_REVISION_DELETE] = 0;
			_sizes[BC_MYPAGE_MAP] = 0;
			_sizes[BC_BARRACKNAME_CHANGE] = 79;
			_sizes[CB_VISIT] = 88;
			_sizes[CB_BUY_THEMA] = 34;
			_sizes[BC_ACCOUNT_PROP] = 0;
			_sizes[CB_CURRENT_BARRACK] = 51;
			_sizes[CB_GEMSCOOL_PCINFO] = 1302;
			_sizes[BC_NORMAL] = 0;
			_sizes[CB_POSE] = 27;
			_sizes[CB_PLACE_CMD] = 58;
			_sizes[CB_CHAT] = 0;
			_sizes[BC_CHAT] = 0;
			_sizes[CB_ECHO_NORMAL] = 0;
			_sizes[CB_JUMP] = 31;
			_sizes[BC_JUMP] = 31;
			_sizes[BC_SERVER_ENTRY] = 22;
			_sizes[CB_PET_PC] = 38;
			_sizes[CB_PET_COMMAND] = 39;
			_sizes[CB_CHANGE_BARRACK_LAYER] = 34;
			_sizes[CB_CHANGE_BARRACK_TARGET_LAYER] = 34;
			_sizes[CB_SELECT_BARRACK_LAYER] = 26;
			_sizes[CB_SCREENSHOT_HASH] = 54;
			_sizes[CB_REQ_SLOT_PRICE] = 22;
			_sizes[BC_REQ_SLOT_PRICE] = 14;
			_sizes[CB_REQ_CHANGE_POSTBOX_STATE] = 35;
			_sizes[CB_REQ_POSTBOX_PAGE] = 26;
			_sizes[CB_REQ_GET_POSTBOX_ITEM] = 1063;
			_sizes[BC_WAIT_QUEUE_ORDER] = 14;
			_sizes[CB_CANCEL_SERVER_WAIT_QUEUE] = 22;
			_sizes[CB_REQ_CHANNEL_TRAFFIC] = 26;
			_sizes[CB_DEBUG_LOG_FILE] = 0;
			_sizes[BC_FAIL_TO_GET_AUTHCODE] = 16;
			_sizes[CB_CLIENT_REMOTE_LOG] = 2584;
			_sizes[BC_RETURN_PC_MARKET_REGISTERED] = 20;
			_sizes[BC_CHARACTER_SLOT_SWAP_SUCCESS] = 16;
			_sizes[CB_CHARACTER_SWAP_SLOT] = 38;
			_sizes[BC_CHARACTER_SLOT_SWAP_FAIL] = 16;
			_sizes[BC_LAYER_CHANGE_SYSTEM_MESSAGE] = 78;
			_sizes[BC_DISCONNECT_PACKET_LOG_COUNT] = 14;
			_sizes[CB_REQ_POSTBOX_REFRESH] = 22;
			_sizes[CS_LOGIN] = 91;
			_sizes[SC_NORMAL] = 0;
			_sizes[SC_FROM_INTEGRATE] = 0;
			_sizes[CS_REGISTER_SNS_ID] = 24;
			_sizes[CS_REQ_SNS_PC_INFO] = 0;
			_sizes[CS_REQ_ADD_FRIEND] = 74;
			_sizes[CS_REQ_BLOCK_FRIEND] = 74;
			_sizes[CS_FRIEND_CMD] = 32;
			_sizes[CS_FRIEND_SET_ADDINFO] = 168;
			_sizes[CS_CHAT] = 0;
			_sizes[CS_GROUP_CHAT_INVITE] = 114;
			_sizes[CS_GROUP_CHAT_INVITE_BY_TAG] = 26;
			_sizes[CS_ALLOW_GROUP_CHAT_TAG_INVITE] = 50;
			_sizes[CS_REFRESH_GROUP_CHAT] = 16;
			_sizes[CS_REQ_CHAT_HISTORY] = 26;
			_sizes[CS_REQ_OUT_ROOM] = 18;
			_sizes[CS_ADD_RELATION_SCORE] = 96;
			_sizes[CS_GET_LIKE_COUNT] = 24;
			_sizes[CS_LIKE_IT] = 96;
			_sizes[CS_UNLIKE_IT] = 32;
			_sizes[CS_LIKE_IT_CONFIRM] = 24;
			_sizes[CS_REQ_RELATED_PC_SESSION] = 24;
			_sizes[CS_REDIS_SKILLPOINT] = 26;
			_sizes[CS_CREATE_GROUP_CHAT] = 16;
			_sizes[CS_PARTY_CLIENT_INFO_SEND] = 0;
			_sizes[CS_NORMAL_GAME_START] = 16;
			_sizes[CS_REQUEST_PVP_RANKING] = 92;
			_sizes[CS_REQUEST_ALL_SEASON_TOP_PVP_RANKING] = 84;
			_sizes[CS_INVITE_PARTY_PVP] = 14;
			_sizes[CS_ACCEPT_PARTY_PVP] = 23;
			_sizes[CS_REQ_MEMBER_LOGOUT_TIME] = 16;
			_sizes[CS_INVITE_GROUPCHAT_ACCEPT] = 135;
			_sizes[CZ_CONNECT] = 1268;
			_sizes[CZ_GAME_READY] = 22;
			_sizes[ZC_ADD_BARRACK_CHARACTER_SLOT_SUCCESS] = 18;
			_sizes[CZ_KEYBOARD_MOVE] = 66;
			_sizes[CZ_EXPECTED_STOP_POS] = 43;
			_sizes[CZ_MOVE_PATH] = 39;
			_sizes[CZ_MOVE_STOP] = 60;
			_sizes[CZ_JUMP] = 60;
			_sizes[CZ_DASHRUN] = 24;
			_sizes[CZ_REST_SIT] = 22;
			_sizes[CZ_REQ_CHAR_SLOT] = 23;
			_sizes[CZ_ON_AIR] = 22;
			_sizes[CZ_ON_GROUND] = 22;
			_sizes[CZ_SKILL_JUMP_REQ] = 42;
			_sizes[CZ_LOGOUT] = 23;
			_sizes[CZ_MOVE_BARRACK] = 31;
			_sizes[CZ_MOVE_ZONE_OK] = 22;
			_sizes[CZ_MOVEMENT_INFO] = 35;
			_sizes[CZ_NOTICE_GUILD_APPLICATION_REQUEST] = 32;
			_sizes[CZ_PARTY_OUT] = 22;
			_sizes[CZ_NGS] = 0;
			_sizes[ZC_NGS] = 0;
			_sizes[CZ_REQ_GM_ORDER_DUMMY_KICK] = 26;
			_sizes[CZ_SKILL_TARGET] = 32;
			_sizes[CZ_SKILL_TARGET_ANI] = 36;
			_sizes[CZ_SKILL_GROUND] = 79;
			_sizes[CZ_SKILL_SELF] = 48;
			_sizes[CZ_SKILL_CANCEL] = 24;
			_sizes[CZ_HOLD] = 23;
			_sizes[CZ_SHOUT] = 0;
			_sizes[CZ_CHAT] = 0;
			_sizes[CZ_SELF_CHAT] = 0;
			_sizes[CZ_CHAT_LOG] = 0;
			_sizes[CZ_ITEM_USE] = 34;
			_sizes[CZ_ITEM_USE_TO_ITEM] = 42;
			_sizes[CZ_ITEM_USE_TO_GROUND] = 42;
			_sizes[CZ_ITEM_DROP] = 34;
			_sizes[CZ_ITEM_EQUIP] = 31;
			_sizes[CZ_ITEM_UNEQUIP] = 23;
			_sizes[CZ_REQ_DELETE_EXPIRED_ITEMS] = 30;
			_sizes[ZC_CHECK_INVINDEX] = 34;
			_sizes[CZ_ITEM_DELETE] = 38;
			_sizes[CZ_ITEM_BUY] = 0;
			_sizes[CZ_ITEM_SELL] = 0;
			_sizes[CZ_ITEMPROPCHANGE] = 38;
			_sizes[CZ_ITEMPROPCHANGE_GEM_ADD] = 26;
			_sizes[CZ_ITEMPROPCHANGE_GEM_DROP] = 50;
			_sizes[CZ_ITEMPROPCHANGE_GEM_POP] = 34;
			_sizes[CZ_ITEMPROPCHANGE_GEM_ALL_SLOT] = 30;
			_sizes[CZ_ITEMPROPCHANGE_ICHOR_RANDOM_OPTION] = 166;
			_sizes[CZ_ITEMPROPCHANGE_ICHOR_RANDOM_OPTION_MAX_VALUE] = 98;
			_sizes[CZ_ITEMPROPCHANGE_OPTION_CHANGE] = 94;
			_sizes[CZ_DIALOG_ACK] = 26;
			_sizes[CZ_DIALOG_SELECT] = 23;
			_sizes[CZ_DIALOG_STRINGINPUT] = 150;
			_sizes[CZ_MOVE_CAMP] = 30;
			_sizes[CZ_CAMPINFO] = 30;
			_sizes[ZC_CAMPINFO] = 22;
			_sizes[CZ_HOUSING_OPEN_EDIT_MODE] = 16;
			_sizes[CZ_HOUSING_CLOSE_EDIT_MODE] = 16;
			_sizes[CZ_HOUSING_REQUEST_GRID_ARRANGED_FURNITURE] = 22;
			_sizes[ZC_HOUSING_READY_GRID] = 0;
			_sizes[ZC_HOUSING_READY_ARRANGED_FURNITURE] = 0;
			_sizes[ZC_HOUSING_START_ARRANGEMENT_FURNITURE] = 14;
			_sizes[CZ_HOUSING_REQUEST_ARRANGEMENT_FURNITURE] = 0;
			_sizes[CZ_HOUSING_CANCEL_ARRANGEMENT_FURNITURE] = 23;
			_sizes[CZ_HOUSING_REQUEST_REMOVE_FURNITURE] = 30;
			_sizes[CZ_HOUSING_REQUEST_REMOVE_FURNITURE_ALOT] = 0;
			_sizes[CZ_HOUSING_REQUEST_REMOVE_ALL_FURNITURE] = 22;
			_sizes[ZC_HOUSING_ANSWER_REMOVE_FURNITURE] = 18;
			_sizes[CZ_HOUSING_REQUEST_ENABLE_MOVE_FURNITURE] = 30;
			_sizes[ZC_HOUSING_ANSWER_ENABLE_MOVE_FURNITURE] = 18;
			_sizes[CZ_HOUSING_REQUEST_MOVE_FURNITURE] = 0;
			_sizes[CZ_HOUSING_REQUEST_GUILD_AGIT_INFO] = 158;
			_sizes[ZC_HOUSING_ANSWER_GUILD_AGIT_INFO] = 138;
			_sizes[CZ_HOUSING_REQUEST_GUILD_AGIT_EXTENSION] = 150;
			_sizes[CZ_HOUSING_REQUEST_GUILD_LAB_USE_RESEARCH] = 27;
			_sizes[CZ_HOUSING_REQUEST_GUILD_LAB_LEVEL_UP] = 27;
			_sizes[CZ_HOUSING_REQUEST_GUILD_LAB_RESEARCH_LEVEL_UP] = 26;
			_sizes[CZ_HOUSING_REQUEST_GUILD_CONTRIBUTION_TO_MILEAGE] = 26;
			_sizes[CZ_HOUSING_REQUEST_GUILD_MILEAGE_TO_CONTRIBUTION] = 26;
			_sizes[CZ_HOUSING_REQUEST_GUILD_CONTIRUBTION_DISTRIBUTE] = 0;
			_sizes[CZ_HOUSING_REQUEST_GUILD_POINT_UP] = 166;
			_sizes[CZ_HOUSING_REQUEST_HOUSING_SHOP_TRADE] = 0;
			_sizes[ZC_HOUSING_CREATE_BG_FURNITURE] = 31;
			_sizes[ZC_HOUSING_MOVE_BG_FURNITURE] = 27;
			_sizes[ZC_HOUSING_REMOVE_BG_FURNITURE] = 14;
			_sizes[CZ_HOUSING_PAGE_SAVE] = 90;
			_sizes[CZ_HOUSING_PAGE_LOAD] = 26;
			_sizes[CZ_HOUSING_PAGE_DELETE] = 26;
			_sizes[CZ_PERSONAL_HOUSING_REQUEST_LEAVE] = 22;
			_sizes[CZ_PERSONAL_HOUSING_REQUEST_BUY_BACKGROUND] = 26;
			_sizes[CZ_PERSONAL_HOUSING_REQUEST_APPLY_BACKGROUND] = 26;
			_sizes[CZ_HOUSING_REQUEST_PREVIEW] = 39;
			_sizes[ZC_HOUSING_ANSWER_PREVIEW] = 0;
			_sizes[ZC_ANCIENT_MON_REG] = 226;
			_sizes[ZC_ANCIENT_MON_UPDATE] = 113;
			_sizes[ZC_ANCIENT_MON_LOAD] = 0;
			_sizes[ZC_ANCIENT_MON_EXP_UP] = 42;
			_sizes[CZ_ANCIENT_MON_COMPOSE] = 50;
			_sizes[CZ_ANCIENT_MON_SELL] = 30;
			_sizes[CZ_ANCIENT_MON_SWAP] = 34;
			_sizes[CZ_ANCIENT_MON_ALLKILL] = 22;
			_sizes[CZ_CLICK_TRIGGER] = 27;
			_sizes[CZ_ROTATE] = 30;
			_sizes[CZ_HEAD_ROTATE] = 30;
			_sizes[CZ_TARGET_ROTATE] = 30;
			_sizes[CZ_POSE] = 47;
			_sizes[CZ_SYSTEM_LOG_TO_SERVER] = 1111;
			_sizes[CZ_CANCEL_INDUN_MATCHING] = 22;
			_sizes[CZ_CANCEL_INDUN_PARTY_MATCHING] = 22;
			_sizes[CZ_PARTY_SHARED_QUEST] = 290;
			_sizes[CZ_REQ_FORGERY] = 42;
			_sizes[CZ_REQ_BUILD_FOODTABLE] = 94;
			_sizes[CZ_REQ_FISHING] = 35;
			_sizes[CZ_REQ_GET_FISHING_ITEM] = 22;
			_sizes[CZ_REQ_FISHING_RANK] = 90;
			_sizes[ZC_ENABLE_ROTATE] = 79;
			_sizes[CZ_REQ_ADVENTURE_BOOK_RANK] = 154;
			_sizes[CZ_REQ_ADVENTURE_BOOK_REWARD] = 86;
			_sizes[CZ_REQ_QUEST_COMPLETE] = 26;
			_sizes[CZ_REQ_GUILD_ASSET_LOG] = 22;
			_sizes[CZ_REQ_COMMON_SKILL_LIST] = 22;
			_sizes[CZ_REG_EXP_ORB_ITEM] = 30;
			_sizes[ZC_REG_EXP_ORB_ITEM] = 22;
			_sizes[ZC_FILL_EXP_ORB] = 22;
			_sizes[CZ_REQ_QUICKSLOT_LIST] = 22;
			_sizes[ZC_ENTER_PC] = 530;
			_sizes[ZC_ENTER_MONSTER] = 0;
			_sizes[ZC_ENTER_DUMMYPC] = 488;
			_sizes[ZC_UPDATED_DUMMYPC] = 446;
			_sizes[ZC_ENTER_ITEM] = 107;
			_sizes[ZC_LEAVE] = 16;
			_sizes[ZC_MOVE_PATH] = 46;
			_sizes[ZC_MOVE_POS] = 50;
			_sizes[ZC_MOVE_BEZIER] = 79;
			_sizes[ZC_MSPD] = 26;
			_sizes[ZC_MOVE_SPEED] = 31;
			_sizes[ZC_MOVE_DIR] = 65;
			_sizes[ZC_EXPECTED_STOPPOS] = 39;
			_sizes[ZC_MOVE_STOP] = 27;
			_sizes[ZC_REST_SIT] = 16;
			_sizes[ZC_JUMP] = 60;
			_sizes[ZC_JUMP_DIR] = 55;
			_sizes[ZC_ORDER_SKILL_JUMP] = 14;
			_sizes[ZC_SKILL_JUMP] = 42;
			_sizes[ZC_SET_POS] = 27;
			_sizes[ZC_FILE_MOVE] = 50;
			_sizes[ZC_MESSAGE] = 0;
			_sizes[ZC_CONNECT_OK] = 0;
			_sizes[ZC_CONNECT_FAILED] = 0;
			_sizes[ZC_START_GAME] = 30;
			_sizes[ZC_MOVE_ZONE] = 11;
			_sizes[ZC_MOVE_BARRACK] = 16;
			_sizes[ZC_MOVE_ZONE_OK] = 61;
			_sizes[ZC_DEAD] = 0;
			_sizes[ZC_RESURRECT] = 22;
			_sizes[ZC_RESURRECT_DIALOG] = 14;
			_sizes[CZ_RESURRECT] = 31;
			_sizes[ZC_RESURRECT_SAVE_POINT_ACK] = 11;
			_sizes[ZC_RESURRECT_HERE_ACK] = 11;
			_sizes[ZC_UPDATED_PCAPPEARANCE] = 446;
			_sizes[ZC_UPDATED_MONSTERAPPEARANCE] = 0;
			_sizes[ZC_ADD_HP] = 26;
			_sizes[ZC_UPDATE_SP] = 19;
			_sizes[ZC_UPDATE_MHP] = 18;
			_sizes[ZC_EXP_UP] = 26;
			_sizes[ZC_EXP_UP_BY_MONSTER] = 30;
			_sizes[ZC_PC_LEVELUP] = 18;
			_sizes[ZC_PC_STAT_AVG] = 34;
			_sizes[ZC_MAX_EXP_CHANGED] = 38;
			_sizes[ZC_UPDATE_ALL_STATUS] = 34;
			_sizes[ZC_CHANGE_RELATION] = 15;
			_sizes[ZC_QUICK_SLOT_LIST] = 0;
			_sizes[ZC_SKILL_LIST] = 0;
			_sizes[ZC_SKILL_ADD] = 0;
			_sizes[ZC_SKILL_REMOVE] = 18;
			_sizes[ZC_SKILL_CAST_CANCEL] = 14;
			_sizes[ZC_SKILL_CAST] = 42;
			_sizes[ZC_SKILL_READY] = 54;
			_sizes[ZC_SKILL_USE_CANCEL] = 14;
			_sizes[ZC_SKILL_DISABLE] = 19;
			_sizes[ZC_SKILL_MELEE_TARGET] = 0;
			_sizes[ZC_SKILL_FORCE_TARGET] = 0;
			_sizes[ZC_SKILL_MELEE_GROUND] = 0;
			_sizes[ZC_SKILL_FORCE_GROUND] = 0;
			_sizes[ZC_SKILL_HIT_INFO] = 0;
			_sizes[ZC_COMMON_SKILL_LIST] = 0;
			_sizes[ZC_ABILITY_LIST] = 0;
			_sizes[CZ_DISPEL_DEBUFF_TOGGLE] = 26;
			_sizes[CZ_JUNGTAN_TOGGLE] = 36;
			_sizes[ZC_BUFF_LIST] = 0;
			_sizes[ZC_BUFF_ADD] = 0;
			_sizes[ZC_BUFF_UPDATE] = 0;
			_sizes[ZC_BUFF_REMOVE] = 24;
			_sizes[ZC_BUFF_CLEAR] = 15;
			_sizes[CZ_BUFF_REMOVE] = 26;
			_sizes[CZ_INTE_WARP] = 26;
			_sizes[ZC_HIT_INFO] = 74;
			_sizes[ZC_HEAL_INFO] = 38;
			_sizes[ZC_CAUTION_DAMAGE_INFO] = 19;
			_sizes[ZC_CAUTION_DAMAGE_RELEASE] = 14;
			_sizes[ZC_KNOCKBACK_INFO] = 74;
			_sizes[ZC_KNOCKDOWN_INFO] = 75;
			_sizes[ZC_CHAT] = 0;
			_sizes[ZC_CHAT_WITH_TEXTCODE] = 18;
			_sizes[ZC_SHOUT] = 0;
			_sizes[ZC_SHOUT_FAILED] = 11;
			_sizes[ZC_TEXT] = 0;
			_sizes[ZC_QUIET] = 11;
			_sizes[ZC_DIALOG_CLOSE] = 16;
			_sizes[ZC_DIALOG_OK] = 0;
			_sizes[ZC_DIALOG_NEXT] = 0;
			_sizes[ZC_DIALOG_SELECT] = 0;
			_sizes[ZC_DIALOG_TRADE] = 43;
			_sizes[ZC_DIALOG_COMMON_TRADE] = 43;
			_sizes[ZC_DIALOG_ITEM_SELECT] = 0;
			_sizes[ZC_DIALOG_NUMBERRANGE] = 0;
			_sizes[ZC_DIALOG_STRINGINPUT] = 0;
			_sizes[ZC_STANCE_CHANGE] = 18;
			_sizes[ZC_ITEM_ADD] = 0;
			_sizes[ZC_ITEM_INVENTORY_LIST] = 0;
			_sizes[ZC_ITEM_INVENTORY_DIVISION_LIST] = 0;
			_sizes[ZC_ITEM_INVENTORY_INDEX_LIST] = 0;
			_sizes[ZC_ITEM_EQUIP_LIST] = 0;
			_sizes[ZC_ITEM_REMOVE] = 28;
			_sizes[ZC_ITEM_USE] = 18;
			_sizes[ZC_ITEM_USE_TO_GROUND] = 26;
			_sizes[ZC_RESET_VIEW] = 16;
			_sizes[ZC_RESTORATION] = 16;
			_sizes[ZC_ROTATE] = 24;
			_sizes[ZC_ROTATE_RESERVED] = 22;
			_sizes[ZC_HEAD_ROTATE] = 22;
			_sizes[ZC_TARGET_ROTATE] = 22;
			_sizes[ZC_QUICK_ROTATE] = 22;
			_sizes[ZC_POSE] = 39;
			_sizes[ZC_DELAYED_ROTATE_MOVE_START] = 26;
			_sizes[ZC_DELAYED_ROTATE_MOVE_END] = 14;
			_sizes[ZC_DUMP_PROPERTY] = 0;
			_sizes[ZC_OBJECT_PROPERTY] = 0;
			_sizes[ZC_OBJECT_PROPERTY_BY_NAMES] = 0;
			_sizes[ZC_ADDON_MSG] = 0;
			_sizes[CZ_UI_EVENT] = 0;
			_sizes[ZC_LOGOUT_OK] = 16;
			_sizes[ZC_PLAY_SOUND] = 19;
			_sizes[ZC_STOP_SOUND] = 18;
			_sizes[ZC_PLAY_MUSICQUEUE] = 20;
			_sizes[ZC_STOP_MUSICQUEUE] = 18;
			_sizes[ZC_PLAY_ANI] = 28;
			_sizes[ZC_PLAY_ANI_SELFISH] = 23;
			_sizes[ZC_CHANGE_ANI] = 48;
			_sizes[ZC_PLAY_ALARMSOUND] = 87;
			_sizes[ZC_STOP_ALARMSOUND] = 14;
			_sizes[ZC_PLAY_EXP_TEXT] = 18;
			_sizes[ZC_PLAY_NAVI_EFFECT] = 154;
			_sizes[CZ_EXCHANGE_REQUEST] = 26;
			_sizes[ZC_EXCHANGE_REQUEST_ACK] = 76;
			_sizes[ZC_EXCHANGE_REQUEST_RECEIVED] = 75;
			_sizes[CZ_EXCHANGE_ACCEPT] = 22;
			_sizes[CZ_EXCHANGE_DECLINE] = 22;
			_sizes[ZC_EXCHANGE_DECLINE_ACK] = 16;
			_sizes[ZC_EXCHANGE_START] = 76;
			_sizes[CZ_EXCHANGE_OFFER] = 42;
			_sizes[ZC_EXCHANGE_OFFER_ACK] = 0;
			_sizes[CZ_EXCHANGE_AGREE] = 22;
			_sizes[ZC_EXCHANGE_AGREE_ACK] = 11;
			_sizes[CZ_EXCHANGE_FINALAGREE] = 22;
			_sizes[ZC_EXCHANGE_FINALAGREE_ACK] = 11;
			_sizes[CZ_EXCHANGE_CANCEL] = 22;
			_sizes[ZC_EXCHANGE_CANCEL_ACK] = 16;
			_sizes[ZC_EXCHANGE_SUCCESS] = 16;
			_sizes[ZC_COOLDOWN_LIST] = 0;
			_sizes[ZC_COOLDOWN_CHANGED] = 31;
			_sizes[ZC_OVERHEAT_CHANGED] = 46;
			_sizes[ZC_TEST_AGENT] = 22;
			_sizes[ZC_TIME_FACTOR] = 14;
			_sizes[ZC_PARTY_ENTER] = 0;
			_sizes[ZC_PARTY_OUT] = 28;
			_sizes[ZC_PARTY_DESTROY] = 19;
			_sizes[ZC_PARTY_INFO] = 0;
			_sizes[ZC_PARTY_LIST] = 0;
			_sizes[ZC_PARTY_INST_INFO] = 0;
			_sizes[ZC_CHANGE_DYNAMICCASTING_MAX_CHANGING_TIME] = 18;
			_sizes[ZC_CHANGE_EQUIP_DURABILITY] = 15;
			_sizes[CZ_DIALOG_TX] = 0;
			_sizes[CZ_REQ_RECIPE] = 0;
			_sizes[ZC_CUSTOM_DIALOG] = 79;
			_sizes[ZC_SESSION_OBJECTS] = 0;
			_sizes[ZC_SESSION_OBJ_ADD] = 0;
			_sizes[ZC_SESSION_OBJ_REMOVE] = 14;
			_sizes[ZC_SESSION_OBJ_TIME] = 18;
			_sizes[CZ_S_OBJ_VALUE_C] = 38;
			_sizes[CZ_REQ_NORMAL_TX] = 57;
			_sizes[ZC_COMMANDER_LOADER_INFO] = 0;
			_sizes[ZC_MOVE_SINGLE_ZONE] = 22;
			_sizes[ZC_BACKTO_ORIGINAL_SERVER] = 12;
			_sizes[CZ_BACKTO_ORIGINAL_SERVER] = 24;
			_sizes[CZ_REQ_NORMAL_TX_NUMARG] = 0;
			_sizes[ZC_UI_OPEN] = 43;
			_sizes[ZC_ENABLE_CONTROL] = 79;
			_sizes[ZC_CHANGE_CAMERA] = 35;
			_sizes[ZC_MONSTER_SDR_CHANGED] = 15;
			_sizes[ZC_MOVE_IGNORE_COLLISION] = 34;
			_sizes[ZC_CHANGE_CAMERA_ZOOM] = 42;
			_sizes[ZC_PLAY_SKILL_ANI] = 86;
			_sizes[ZC_PLAY_SKILL_CAST_ANI] = 34;
			_sizes[CZ_REQ_ITEM_GET] = 26;
			_sizes[ZC_ITEM_GET] = 22;
			_sizes[CZ_GUARD] = 31;
			_sizes[ZC_GUARD] = 23;
			_sizes[ZC_STAMINA] = 14;
			_sizes[ZC_ADD_STAMINA] = 14;
			_sizes[ZC_GM_ORDER] = 14;
			_sizes[ZC_MYPC_ENTER] = 27;
			_sizes[ZC_LOCK_KEY] = 79;
			_sizes[CZ_PREMIUM_ENCHANTCHIP] = 38;
			_sizes[CZ_PREMIUM_GACHACUBE] = 22;
			_sizes[CZ_PREMIUM_GACHACUBE_LEGEND] = 23;
			_sizes[ZC_SAVE_INFO] = 16;
			_sizes[CZ_SAVE_INFO] = 0;
			_sizes[ZC_OPTION_LIST] = 0;
			_sizes[ZC_SKILLMAP_LIST] = 0;
			_sizes[CZ_FOOD_TABLE_TITLE] = 91;
			_sizes[CZ_USE_TP_AND_ENTER_INDUN] = 534;
			_sizes[CZ_USE_RANKRESET_ITEM] = 32;
			_sizes[CZ_REQ_RANKRESET_SYSTEM] = 26;
			_sizes[CZ_GIVEITEM_TO_DUMMYPC] = 34;
			_sizes[ZC_SET_LAYER] = 15;
			_sizes[ZC_CREATE_LAYERBOX] = 42;
			_sizes[ZC_RESET_BOX] = 15;
			_sizes[ZC_CREATE_SCROLLLOCKBOX] = 42;
			_sizes[ZC_REMOVE_SCROLLLOCKBOX] = 14;
			_sizes[CZ_DYNAMIC_CASTING_START] = 51;
			_sizes[CZ_DYNAMIC_CASTING_END] = 33;
			_sizes[ZC_CASTING_SPEED] = 26;
			_sizes[CZ_SKILL_CANCEL_SCRIPT] = 22;
			_sizes[ZC_LEAVE_TRIGGER] = 16;
			_sizes[ZC_BORN] = 14;
			_sizes[ZC_ACHIEVE_POINT_LIST] = 0;
			_sizes[ZC_ACHIEVE_POINT] = 22;
			_sizes[CZ_ACHIEVE_EQUIP] = 26;
			_sizes[ZC_ACHIEVE_EQUIP] = 34;
			_sizes[CZ_ACHIEVE_REWARD] = 26;
			_sizes[CZ_CHANGE_CONFIG] = 30;
			_sizes[CZ_CHANGE_CONFIG_STR] = 46;
			_sizes[ZC_WORLD_MSG] = 47;
			_sizes[ZC_ENABLE_SHOW_ITEM_GET] = 12;
			_sizes[ZC_LOGIN_TIME] = 18;
			_sizes[ZC_GIVE_EXP_TO_PC] = 50;
			_sizes[ZC_LAYER_PC_LIST] = 0;
			_sizes[ZC_LAYER_PC_SOBJ_PROP] = 0;
			_sizes[CZ_CUSTOM_COMMAND] = 38;
			_sizes[CZ_ADD_HELP] = 26;
			_sizes[ZC_LAYER_INFO] = 14;
			_sizes[CZ_CHAT_MACRO] = 158;
			_sizes[ZC_CHAT_MACRO_LIST] = 0;
			_sizes[ZC_RULLET_LIST] = 0;
			_sizes[ZC_QUICKSLOT_REGISTER] = 50;
			_sizes[CZ_QUICKSLOT_LIST] = 0;
			_sizes[CZ_DOUBLE_ITEM_EQUIP] = 40;
			_sizes[ZC_TRICK_PACKET] = 0;
			_sizes[ZC_COOLDOWN_RATE] = 26;
			_sizes[ZC_MAP_REVEAL_LIST] = 0;
			_sizes[CZ_MAP_REVEAL_INFO] = 158;
			_sizes[CZ_MAP_SEARCH_INFO] = 67;
			_sizes[ZC_EXEC_CLIENT_SCP] = 0;
			_sizes[ZC_SET_NPC_STATE] = 22;
			_sizes[ZC_NPC_STATE_LIST] = 0;
			_sizes[CZ_QUEST_NPC_STATE_CHECK] = 26;
			_sizes[ZC_RANK_ACHIEVE_ADD] = 18;
			_sizes[CZ_IES_MODIFY_INFO] = 0;
			_sizes[ZC_IES_MODIFY_INFO] = 0;
			_sizes[ZC_IES_MODIFY_LIST] = 0;
			_sizes[CZ_IES_REVISION_DELETE] = 0;
			_sizes[ZC_IES_REVISION_DELETE] = 0;
			_sizes[ZC_EQUIP_ITEM_REMOVE] = 22;
			_sizes[ZC_SOLD_ITEM_LIST] = 0;
			_sizes[ZC_SOLD_ITEM_DIVISION_LIST] = 0;
			_sizes[CZ_SOLD_ITEM] = 31;
			_sizes[CZ_WAREHOUSE_CMD] = 48;
			_sizes[CZ_SWAP_ETC_INV_CHANGE_INDEX] = 47;
			_sizes[CZ_SORT_INV] = 24;
			_sizes[CZ_EXTEND_WAREHOUSE] = 23;
			_sizes[CZ_CAST_CONTROL_SHOT] = 22;
			_sizes[ZC_PC_PROP_UPDATE] = 15;
			_sizes[ZC_SHOP_POINT_UPDATE] = 58;
			_sizes[CZ_SHOP_POINT_GET] = 54;
			_sizes[CZ_CLIENT_DAMAGE] = 26;
			_sizes[CZ_CLIENT_ATTACK] = 27;
			_sizes[ZC_SYSTEM_MSG] = 0;
			_sizes[ZC_FSM_MOVE] = 0;
			_sizes[CZ_QUEST_CHECK_SAVE] = 62;
			_sizes[CZ_SPRAY_REQ_INFO] = 26;
			_sizes[CZ_SPRAY_DRAW_INFO] = 0;
			_sizes[ZC_SPRAY_ID] = 22;
			_sizes[ZC_SPRAY_DRAW_INFO] = 0;
			_sizes[ZC_MONSTER_LIFETIME] = 18;
			_sizes[ZC_SPRAY_LIKE_LIST] = 0;
			_sizes[ZC_SHARED_MSG] = 14;
			_sizes[CZ_REQ_TX_ITEM] = 0;
			_sizes[ZC_TEST_DBG] = 0;
			_sizes[ZC_MONSTER_DIST] = 0;
			_sizes[ZC_RESET_SKILL_FORCEID] = 14;
			_sizes[ZC_EMOTICON] = 22;
			_sizes[ZC_SHOW_EMOTICON] = 22;
			_sizes[ZC_TREASUREMARK_BY_MAP] = 0;
			_sizes[ZC_SHOW_LOCAL_MAP] = 0;
			_sizes[ZC_FIX_ANIM] = 78;
			_sizes[ZC_MOVE_ANIM] = 16;
			_sizes[CZ_FLEE_OBSTACLE] = 38;
			_sizes[ZC_HOLD_MOVE_PATH] = 15;
			_sizes[ZC_ENTER_HOOK] = 14;
			_sizes[ZC_LEAVE_HOOK] = 14;
			_sizes[ZC_GROUND_EFFECT] = 54;
			_sizes[ZC_FLY] = 22;
			_sizes[ZC_FLY_MATH] = 27;
			_sizes[ZC_FLY_OPTION] = 18;
			_sizes[ZC_FLY_HEIGHT] = 18;
			_sizes[ZC_UPDATE_SHIELD] = 18;
			_sizes[ZC_SHOW_MODEL] = 19;
			_sizes[ZC_SHOW_SCENE_MODEL] = 15;
			_sizes[ZC_SKILL_RANGE_DBG] = 74;
			_sizes[ZC_SKILL_RANGE_FAN] = 50;
			_sizes[ZC_SKILL_RANGE_SQUARE] = 52;
			_sizes[ZC_SKILL_RANGE_CIRCLE] = 40;
			_sizes[ZC_POS_DBG] = 38;
			_sizes[ZC_TEAMID] = 15;
			_sizes[ZC_PC] = 0;
			_sizes[CZ_LOG] = 0;
			_sizes[ZC_MOTIONBLUR] = 15;
			_sizes[ZC_PLAY_FORCE] = 82;
			_sizes[ZC_CAST_TARGET] = 18;
			_sizes[ZC_START_INFO] = 0;
			_sizes[ZC_JOB_EXP_UP] = 26;
			_sizes[ZC_JOB_PTS] = 22;
			_sizes[ZC_MON_STAMINA] = 26;
			_sizes[CZ_CUSTOM_SCP] = 26;
			_sizes[ZC_VIEW_FOCUS] = 28;
			_sizes[ZC_HARDCODED_SKILL] = 30;
			_sizes[CZ_HARDCODED_SKILL] = 46;
			_sizes[ZC_FORCE_MOVE] = 34;
			_sizes[ZC_HSKILL_CONTROL] = 26;
			_sizes[ZC_CANCEL_DEADEVENT] = 14;
			_sizes[ZC_ACTION_PKS] = 39;
			_sizes[CZ_HARDCODED_ITEM] = 34;
			_sizes[CZ_BRIQUET] = 0;
			_sizes[CZ_CANCEL_TRANSFORM_SKILL] = 22;
			_sizes[ZC_VIBRATE] = 34;
			_sizes[ZC_COUNTER_MOVE] = 14;
			_sizes[CZ_COUNTER_ATTACK] = 26;
			_sizes[CZ_CLIENT_DIRECT] = 42;
			_sizes[ZC_CLIENT_DIRECT] = 34;
			_sizes[ZC_OWNER] = 18;
			_sizes[ZC_GD_RANK] = 14;
			_sizes[CZ_RUN_BGEVENT] = 86;
			_sizes[ZC_ADD_SKILL_EFFECT] = 22;
			_sizes[ZC_ITEM_DROPABLE] = 14;
			_sizes[CZ_ITEM_DROP_TO_OBJECT] = 38;
			_sizes[ZC_NORMAL] = 0;
			_sizes[CZ_G_QUEST_CHECK] = 26;
			_sizes[ZC_MOVE_PATH_MATH] = 34;
			_sizes[ZC_SHOW_GROUND_ITEM_MARK] = 34;
			_sizes[ZC_HELP_LIST] = 0;
			_sizes[ZC_HELP_ADD] = 15;
			_sizes[ZC_STD_ANIM] = 15;
			_sizes[CZ_CLIENT_HIT_LIST] = 0;
			_sizes[ZC_PC_ATKSTATE] = 15;
			_sizes[ZC_SEND_PREMIUM_STATE] = 20;
			_sizes[CZ_HELP_READ_TYPE] = 30;
			_sizes[CZ_MOVE_PATH_END] = 22;
			_sizes[ZC_COLL_DAMAGE] = 15;
			_sizes[CZ_KEYBOARD_BEAT] = 22;
			_sizes[CZ_MOVEHIT_SCP] = 34;
			_sizes[ZC_SYNC_START] = 18;
			_sizes[ZC_SYNC_END] = 18;
			_sizes[ZC_SYNC_EXEC] = 14;
			_sizes[ZC_SYNC_EXEC_BY_SKILL_TIME] = 22;
			_sizes[CZ_STOP_TIMEACTION] = 23;
			_sizes[CZ_REQ_DUMMYPC_INFO] = 30;
			_sizes[CZ_VISIT_BARRACK] = 86;
			_sizes[CZ_SPC_SKILL_POS] = 34;
			_sizes[CZ_REQ_MINITEXT] = 278;
			_sizes[ZC_PC_MOVE_STOP] = 52;
			_sizes[CZ_SKILL_TOOL_GROUND_POS] = 39;
			_sizes[CZ_CHANGE_HEAD] = 86;
			_sizes[CZ_CREATE_ARROW_CRAFT] = 26;
			_sizes[CZ_EXCHANGE_ANTIQUE] = 34;
			_sizes[CZ_REQ_GM_ORDER] = 214;
			_sizes[CZ_REPORT_AUTOBOT] = 86;
			_sizes[CZ_REPORT_PVP_ZOOM] = 22;
			_sizes[CZ_SCREENSHOT_HASH] = 55;
			_sizes[CZ_REQ_MOVE_TO_INDUN] = 30;
			_sizes[CZ_CLEAR_INDUN_REG] = 22;
			_sizes[CZ_REQ_REGISTER_TO_INDUN] = 26;
			_sizes[CZ_REQ_GUILD_MEMBER_AUTHORITY] = 35;
			_sizes[CZ_TPSHOP_RTPP_FOR_TEST] = 22;
			_sizes[CZ_REQ_UNDERSTAFF_ENTER_ALLOW] = 22;
			_sizes[CZ_REQ_UNDERSTAFF_ENTER_ALLOW_WITH_PARTY] = 26;
			_sizes[ZC_PLAY_PAIR_ANIMATION] = 340;
			_sizes[ZC_PLAY_ATTACH_MODEL_ANIM] = 26;
			_sizes[ZC_FISHING_ITEM_LIST] = 0;
			_sizes[ZC_ADVENTURE_BOOK_INFO] = 0;
			_sizes[ZC_CANCEL_MOUSE_MOVE] = 14;
			_sizes[ZC_COLONY_OCCUPATION_INFO] = 0;
			_sizes[ZC_BROAD_CAST_MY_INFO] = 31;
			_sizes[CZ_REQ_RETURN_TO_CITY_FROM_COLONY_WAR] = 22;
			_sizes[ZC_ATTENDANCE_RECEIPT_REWARD] = 0;
			_sizes[CZ_ATTENDANCE_REWARD_CLICK] = 26;
			_sizes[ZC_ATTENDANCE_REWARD_CHECK_UI_ON] = 12;
			_sizes[ZC_ERROR_INFO] = 0;
			_sizes[ZC_RESERVE_PROPERTY] = 0;
			_sizes[ZC_REDIS_RANKING_INFO] = 0;
			_sizes[CZ_REQUEST_COLONYWAR_ENDTIME] = 22;
			_sizes[ZC_RESPONSE_COLONYWAR_ENDTIME] = 26;
			_sizes[ZC_ALTER_HIT_RADIUS] = 22;
			_sizes[ZC_SET_COLONY_TIME_CHEAT_FAIL] = 16;
			_sizes[ZC_SET_COLONY_TIME_CHEAT_SUCCESS] = 16;
			_sizes[ZC_GUILD_BUILDING_OBJECT_ADD] = 0;
			_sizes[ZC_GUILD_BUILDING_OBJECT_REMOVE] = 0;
			_sizes[ZC_START_IMITATING_ANIMATION] = 18;
			_sizes[ZC_STOP_IMITATING_ANIMATION] = 14;
			_sizes[CZ_START_IMITATING_ANIMATION_ACK] = 22;
			_sizes[CZ_FOLLOW_TO_ACTOR_ACK] = 22;
			_sizes[ZC_COLONY_TAX_TOTAL_AMOUNT] = 50;
			_sizes[ZC_COLONY_TAX_RATE_LIST] = 0;
			_sizes[ZC_COLONY_TAX_LORD_READY] = 153;
			_sizes[ZC_COLONY_TAX_LORD_START] = 38;
			_sizes[ZC_COLONY_TAX_LORD_END] = 14;
			_sizes[ZC_COLONY_TAX_RATE_SET] = 42;
			_sizes[ZC_COLONY_TAX_CHEQUE_LIST] = 0;
			_sizes[CZ_COLONY_TAX_RATE_REQ_SET] = 30;
			_sizes[CZ_COLONY_TAX_CHEQUE_REQ_LIST] = 22;
			_sizes[CZ_COLONY_TAX_CHEQUE_REQ_SEND] = 0;
			_sizes[CZ_COLONY_TAX_HISTORY_REQ_LIST] = 22;
			_sizes[ZC_COLONY_TAX_HISTORY_LIST] = 0;
			_sizes[ZC_COLONY_TAX_PAYMENT_LIST] = 0;
			_sizes[CZ_COLONY_TAX_PAYMENT_REQ_RECV] = 30;
			_sizes[CZ_COLONY_TAX_PAYMENT_REQ_LIST] = 22;
			_sizes[CZ_REQUEST_RVR_ENDTIME] = 22;
			_sizes[ZC_RESPONSE_RVR_ENDTIME] = 26;
			_sizes[CZ_REGISTER_NEW_GUILD_EMBLEM] = 20107;
			_sizes[CZ_CHANGE_GUILD_EMBLEM] = 20108;
			_sizes[ZC_UPDATE_GUILD_EMBLEM] = 24;
			_sizes[CZ_REQUEST_CERTAIN_GUILD_EMBLEM] = 32;
			_sizes[ZC_RESPONSE_CERTAIN_GUILD_EMBLEM] = 20040;
			_sizes[CZ_REQUEST_GUILD_EMBLEM_INFO] = 32;
			_sizes[ZC_RESPONSE_GUILD_EMBLEM_INFO] = 102;
			_sizes[CZ_REQUEST_GUILD_INDEX] = 30;
			_sizes[ZC_RESPONSE_GUILD_INDEX] = 24;
			_sizes[CZ_REPORT_GUILDEMBLEM] = 86;
			_sizes[ZC_DELETE_GUILD_EMBLEM] = 24;
			_sizes[CZ_DELETE_GUILD_EMBLEM] = 22;
			_sizes[ZC_ADDITIONAL_SKILL_POINT] = 0;
			_sizes[ZC_START_FIELDBOSS_WORLD_EVENT] = 0;
			_sizes[ZC_END_FIELDBOSS_WORLD_EVENT] = 16;
			_sizes[ZC_FIELDBOSS_REMOVE_ITEM] = 14;
			_sizes[CZ_BID_FIELDBOSS_WORLD_EVENT] = 22;
			_sizes[ZC_WIN_FIELDBOSS_WORLD_EVENT_ITEM] = 14;
			_sizes[ZC_LOSE_FIELDBOSS_WORLD_EVENT_ITEM] = 14;
			_sizes[ZC_START_CASUAL_GAMBLE] = 0;
			_sizes[ZC_CASUAL_GAMBLE_ITEM_GET] = 18;
			_sizes[CZ_REQUEST_CASUAL_GAMBLE] = 22;
			_sizes[ZC_END_CASUAL_GAMBLE] = 16;
			_sizes[ZC_NXA_REQ_TICKET] = 16;
			_sizes[CZ_NXA_TICKET] = 1046;
			_sizes[CZ_NXA_REQ_BALANCE] = 22;
			_sizes[ZC_NXA_BALANCE] = 40;
			_sizes[CZ_NXA_REQ_ITEMLIST] = 23;
			_sizes[ZC_NXA_ITEMLIST] = 0;
			_sizes[CZ_NXA_REQ_PURCHASE] = 27;
			_sizes[ZC_NXA_PURCHASE] = 4106;
			_sizes[CZ_NXA_REQ_PICKUP_READY_ITEMS] = 2071;
			_sizes[CZ_NXA_REQ_PURCHASE_CANCEL] = 22;
			_sizes[ZC_NXA_SELLITEMLIST] = 0;
			_sizes[ZC_CASH_INVENTORY_LIST] = 0;
			_sizes[CZ_NEXON_PAYMENT_PAGE] = 22;
			_sizes[ZC_NEXON_PAYMENT_PAGE] = 522;
			_sizes[ZC_ADD_CHATBALLOON_SKIN] = 0;
			_sizes[CZ_SET_CHATBALLOON_SKIN] = 26;
			_sizes[ZC_SET_CHATBALLOON_SKIN] = 34;
			_sizes[ZC_UPDATE_CHATBALLOON_SKIN] = 16;
			_sizes[CZ_DO_CLIENT_MOVE_CHECK] = 22;
			_sizes[ZC_IS_SUMMONING_MONSTER] = 15;
			_sizes[CZ_MYPAGE_COMMENT_ADD] = 290;
			_sizes[CZ_MYPAGE_COMMENT_DELETE] = 30;
			_sizes[CZ_GET_TARGET_MYPAGE] = 26;
			_sizes[CZ_ON_MYPAGE_MODE] = 26;
			_sizes[CZ_RESET_SOCIAL_MODE] = 22;
			_sizes[CZ_GUESTPAGE_COMMENT_ADD] = 290;
			_sizes[CZ_GET_TARGET_GUESTPAGE] = 26;
			_sizes[CZ_ADD_SELLMODE_ITEM] = 42;
			_sizes[CZ_DELETE_SELLMODE_ITEM] = 30;
			_sizes[CZ_ON_SELLITEM_MODE] = 26;
			_sizes[CZ_ON_ITEMBUY_MODE] = 0;
			_sizes[ZC_MYPAGE_MAP] = 0;
			_sizes[ZC_GUESTPAGE_MAP] = 0;
			_sizes[ZC_ON_MYPAGE_MODE] = 0;
			_sizes[ZC_RESET_SOCIAL_MODE] = 14;
			_sizes[ZC_ON_BUYITEM_MODE] = 0;
			_sizes[CZ_STOP_ALLPC] = 22;
			_sizes[CZ_COMPLETE_PRELOAD] = 26;
			_sizes[CZ_MGAME_JOIN_CMD] = 58;
			_sizes[ZC_ATTACH_TO_OBJ] = 53;
			_sizes[ZC_DETACH_FROM_OBJ] = 18;
			_sizes[ZC_RUN_FROM] = 18;
			_sizes[ZC_LOOKAT_OBJ] = 18;
			_sizes[CZ_SKILL_CELL_LIST] = 0;
			_sizes[CZ_DIRECTION_PROCESS] = 34;
			_sizes[CZ_DIRECTION_MOVE_STATE] = 0;
			_sizes[ZC_TO_ALL_CLIENT] = 0;
			_sizes[ZC_TO_CLIENT] = 0;
			_sizes[CZ_REWARD_CMD] = 26;
			_sizes[CZ_PROPERTY_COMPARE] = 28;
			_sizes[ZC_PROPERTY_COMPARE] = 0;
			_sizes[ZC_PROPERTY_COMPARE_FOR_ACT] = 0;
			_sizes[ZC_SEND_CASH_VALUE] = 0;
			_sizes[ZC_FACTION] = 18;
			_sizes[ZC_BEGIN_KILL_LOG] = 16;
			_sizes[ZC_END_KILL_LOG] = 16;
			_sizes[ZC_CLEAR_KILL_LOG] = 16;
			_sizes[CZ_NPC_AUCTION_CMD] = 42;
			_sizes[ZC_DIRECTION_APC] = 30;
			_sizes[ZC_BGMODEL_ANIM_INFO] = 19;
			_sizes[ZC_ATTACH_BY_KNOCKBACK] = 42;
			_sizes[CZ_OBJECT_MOVE] = 42;
			_sizes[CZ_CONTROL_OBJECT_ROTATE] = 34;
			_sizes[CZ_SUMMON_COMMAND] = 30;
			_sizes[CZ_VEHICLE_RIDE] = 27;
			_sizes[CZ_REQ_ACHIEVE_RANK_PAGE_INFO] = 90;
			_sizes[ZC_SPC_TRIGGER_EXEC] = 34;
			_sizes[CZ_REQ_MGAME_VIEW] = 30;
			_sizes[CZ_REQ_MGAME_CHAT] = 0;
			_sizes[CZ_TOURNAMENT_GIFT] = 30;
			_sizes[CZ_PARTY_INVITE_ACCEPT] = 153;
			_sizes[CZ_PARTY_INVITE_CANCEL] = 103;
			_sizes[CZ_PARTY_PROP_CHANGE] = 159;
			_sizes[CZ_REQ_MARKET_REGISTER] = 56;
			_sizes[CZ_REQ_MARKET_MINMAX_INFO] = 30;
			_sizes[CZ_REQ_MARKET_BUY] = 0;
			_sizes[CZ_REQ_CABINET_LIST] = 22;
			_sizes[CZ_REQ_GET_CABINET_ITEM] = 38;
			_sizes[CZ_REQ_CANCEL_MARKET_ITEM] = 30;
			_sizes[CZ_OBJ_RECORD_POS] = 0;
			_sizes[CZ_FORMATION_CMD] = 44;
			_sizes[CZ_REGISTER_AUTOSELLER] = 0;
			_sizes[CZ_INV_ITEM_LOCK] = 31;
			_sizes[CZ_OPEN_AUTOSELLER] = 94;
			_sizes[CZ_BUY_AUTOSELLER_ITEMS] = 0;
			_sizes[CZ_SELL_MY_AUTOSELLER_ITEMS] = 0;
			_sizes[CZ_PUZZLE_CRAFT] = 0;
			_sizes[CZ_PET_EQUIP] = 46;
			_sizes[CZ_PET_AUTO_ATK] = 23;
			_sizes[ZC_PET_AUTO_ATK] = 23;
			_sizes[ZC_TO_SOMEWHERE_CLIENT] = 0;
			_sizes[CZ_REVEAL_NPC_STATE] = 26;
			_sizes[CZ_CHANGE_CHANNEL] = 24;
			_sizes[CZ_REQ_CHANNEL_TRAFFICS] = 24;
			_sizes[CZ_BUY_PROPERTYSHOP_ITEM] = 0;
			_sizes[CZ_SKILL_USE_HEIGHT] = 26;
			_sizes[CZ_CHANGE_GUILD_NEUTRALITY] = 22;
			_sizes[CZ_SAVE_GUILD_BOARD] = 122;
			_sizes[CZ_DELETE_PARTY_EVENT] = 32;
			_sizes[CZ_PING] = 22;
			_sizes[ZC_PING] = 22;
			_sizes[CZ_REQ_REMAIN_NEXONCASH] = 22;
			_sizes[CZ_REQ_OPEN_INGAMESHOP_UI] = 22;
			_sizes[CZ_REQ_BUY_INGAMESHOP_ITEM] = 90;
			_sizes[CZ_REQ_BUY_ALL_INGAMESHOP_ITEM] = 22;
			_sizes[CZ_REQ_PICKUP_CASHITEM] = 49;
			_sizes[CZ_REQ_REFUND_CASHITEM] = 45;
			_sizes[ZC_XIGNCODE_BUFFER] = 536;
			_sizes[CZ_XIGNCODE_BUFFER] = 536;
			_sizes[CZ_SYSTEM_LOG_SAVE_TO_MONGODB] = 292;
			_sizes[CZ_CHANGE_TITLE] = 86;
			_sizes[CZ_PC_COMMENT_CHANGE] = 0;
			_sizes[CZ_AUTTOSELLER_BUYER_CLOSE] = 30;
			_sizes[CZ_REQ_ITEM_LIST] = 23;
			_sizes[CZ_REQ_ACC_WARE_VIS_LOG] = 22;
			_sizes[CZ_HIT_MISSILE] = 26;
			_sizes[CZ_PARTY_JOIN_BY_LINK] = 39;
			_sizes[CZ_PVP_ZONE_CMD] = 38;
			_sizes[CZ_PVP_CHAT] = 0;
			_sizes[CZ_CARDBATTLE_CMD] = 38;
			_sizes[CZ_REQ_UPDATE_CONTENTS_SESSION] = 22;
			_sizes[CZ_REQ_FRIENDLY_FIGHT] = 27;
			_sizes[CZ_HARDSKILL_POS_LIST] = 0;
			_sizes[CZ_CART_POSITION] = 38;
			_sizes[CZ_REQ_RIDE_CART] = 30;
			_sizes[CZ_DUMMYPC_SKILL_POS] = 38;
			_sizes[CZ_PARTY_MEMBER_SKILL_USE] = 0;
			_sizes[CZ_PARTY_MEMBER_SKILL_ACCEPT] = 35;
			_sizes[CZ_UDP_RTT_CHECK] = 26;
			_sizes[ZC_UDP_RTT_CHECK] = 18;
			_sizes[CZ_UDP_RTT_CHECK_ACK] = 30;
			_sizes[CZ_HEARTBEAT] = 26;
			_sizes[CZ_PARTY_INVENTORY_LOAD] = 24;
			_sizes[CZ_REQ_MOVE_PARTYINV_TO_ACCOUNT] = 0;
			_sizes[CZ_PVP_COMMAND] = 35;
			_sizes[CZ_REQ_CancelGachaCube] = 22;
			_sizes[CZ_WAREHOUSE_TAKE_LIST] = 0;
			_sizes[CZ_SAVE_AUTO_MACRO] = 0;
			_sizes[CZ_REQUEST_LOAD_ITEM_BUY_LIMIT] = 22;
			_sizes[CZ_AUTO_STATE] = 23;
			_sizes[CZ_FIXED_NOTICE_SHOW] = 22;
			_sizes[CZ_SAGE_SKILL_GO_FRIEND] = 102;
			_sizes[CZ_RUN_GAMEEXIT_TIMER] = 86;
			_sizes[CZ_REQUEST_CHANGE_NAME] = 78;
			_sizes[CZ_REQUEST_CHANGE_PET_NAME] = 94;
			_sizes[ZC_HOLD_EXP_BOOK_TIME] = 37;
			_sizes[CZ_HOLD_EXP_BOOK_TIME] = 26;
			_sizes[ZC_BUFF_UPDATE_TIME] = 34;
			_sizes[CZ_CYOU_CTU_CLIENT_MSG] = 1054;
			_sizes[CZ_RUN_FUNCTION_DUMP] = 0;
			_sizes[ZC_RUN_FUNCTION_DUMP] = 0;
			_sizes[ZC_RUN_FUNCTION_DUMP_ERROR] = 0;
			_sizes[ZC_RUN_FUNCTION_DUMP_PRINT] = 0;
			_sizes[ZC_ATTACH_TO_SLOT] = 26;
			_sizes[CZ_REQ_GUILD_NEUTRALITY_ALARM] = 26;
			_sizes[CZ_SYNC_POS] = 38;
			_sizes[CZ_DISCONNECT_REASON_FOR_LOG] = 0;
			_sizes[CZ_LOAD_COMPLETE] = 22;
			_sizes[ZC_LOAD_COMPLETE] = 16;
			_sizes[CZ_ACCEPT_CHALLENGE_MODE] = 26;
			_sizes[CZ_ACCEPT_CHALLENGE_MODE_BY_PCBANG] = 26;
			_sizes[CZ_ACCEPT_NEXT_LEVEL_CHALLENGE_MODE] = 26;
			_sizes[CZ_ACCEPT_STOP_LEVEL_CHALLENGE_MODE] = 26;
			_sizes[ZC_UPDATE_CHALLENGE_MODE_WARP_PORTAL_MARK] = 23;
			_sizes[ZC_CYOU_KICK_USER_EXIT_CLIENT] = 16;
			_sizes[CZ_REQ_PARTY_INFO] = 22;
			_sizes[CZ_BADPLAYER_REPORT] = 158;
			_sizes[CZ_REQ_RETURN_ORIGIN_SERVER] = 22;
			_sizes[CZ_ANS_GIVEUP_PREV_PLAYING_INDUN] = 23;
			_sizes[ZC_SEND_JSON_DUMP] = 0;
			_sizes[CZ_SEND_JSON_DUMP] = 0;
			_sizes[CZ_CLIENT_REMOTE_LOG] = 2584;
			_sizes[ZC_FOLLOW_TO_ACTOR] = 39;
			_sizes[ZC_STOP_FOLLOW_TO_ACTOR] = 14;
			_sizes[ZC_FIXCAMERA] = 26;
			_sizes[ZC_CANCEL_FIXCAMERA] = 16;
			_sizes[CZ_REQ_PCBANG_SHOP_UI] = 26;
			_sizes[CZ_REQ_PCBANG_SHOP_CONNECT_REWARD] = 86;
			_sizes[CZ_REQ_PCBANG_SHOP_TOTAL_REWARD] = 26;
			_sizes[CZ_REQ_PCBANG_SHOP_PURCHASE] = 26;
			_sizes[CZ_REQ_PCBANG_SHOP_RENTAL] = 26;
			_sizes[CZ_REQ_PCBANG_SHOP_REFRESH] = 22;
			_sizes[ZC_PCBANG_SHOP_COMMON] = 66;
			_sizes[ZC_PCBANG_SHOP_MAIN] = 0;
			_sizes[ZC_PCBANG_SHOP_POINTSHOP_CATALOG] = 0;
			_sizes[ZC_PCBANG_SHOP_POINTSHOP_BUY_COUNT] = 0;
			_sizes[ZC_PCBANG_SHOP_RENTAL] = 0;
			_sizes[ZC_PCBANG_SHOP_GUIDE] = 0;
			_sizes[ZC_PCBANG_SHOP_REWARD] = 0;
			_sizes[ZC_PCBANG_STATE] = 15;
			_sizes[ZC_PCBANG_POINT] = 22;
			_sizes[ZC_SET_WEBSERVICE_URL] = 266;
			_sizes[CZ_CREATE_GUILD_BY_WEB] = 71;
			_sizes[CZ_GUILD_MEMBER_INVITE_BY_WEB] = 95;
			_sizes[ZC_GUILD_MEMBER_INVITE_BY_WEB] = 91;
			_sizes[CZ_WEEKLY_BOSS_INDUN_ENTER] = 23;
			_sizes[CZ_GUILD_MEMBER_INVITE_ACCEPT_BY_WEB] = 102;
			_sizes[CZ_GUILD_APPLICATION_USER_ACCEPT] = 95;
			_sizes[ZC_DECREASE_SILVER] = 14;
			_sizes[CZ_POST_GUILD_EMBLEM] = 20026;
			_sizes[CZ_REQUEST_CERTAIN_WEBSERVICE_URL] = 24;
			_sizes[ZC_RESPONSE_CERTAIN_WEBSERVICE_URL] = 268;
			_sizes[CZ_GUILD_AGIT_ENTER] = 159;
			_sizes[ZC_SOLD_ITEM_NOTICE] = 158;
			_sizes[ZC_RELOAD_SELL_LIST] = 16;
			_sizes[ZC_NOTICE_BROKEN_SYNC_MARKET_ITEM] = 18;
			_sizes[CZ_SWAP_ITEM_IN_WAREHOUSE] = 46;
			_sizes[ZC_SWAP_ITEM_IN_WAREHOUSE_FAIL] = 18;
			_sizes[CZ_SEND_BEAUTYSHOP_PURCHASE_LIST] = 0;
			_sizes[ZC_RES_BEAUTYSHOP_PURCHASED_HAIR_LIST] = 0;
			_sizes[CZ_REQ_BEAUTYSHOP_INFO] = 23;
			_sizes[CZ_SEND_BEAUTYSHOP_TRYITON_LIST] = 0;
			_sizes[CZ_SEND_BEAUTYSHOP_TRYITON_CANCEL] = 22;
			_sizes[ZC_VERTICAL_MOTION] = 23;
			_sizes[CZ_REQ_PLAY_FLUTING] = 31;
			_sizes[ZC_PLAY_FLUTING] = 24;
			_sizes[CZ_REQ_READY_FLUTING] = 23;
			_sizes[ZC_READY_FLUTING] = 15;
			_sizes[CZ_REQ_STOP_FLUTING] = 31;
			_sizes[ZC_STOP_FLUTING] = 23;
			_sizes[ZC_STOP_FLUTING_ALL] = 14;
			_sizes[CZ_REQ_SOLO_DUNGEON_REWARD] = 22;
			_sizes[CZ_REQ_SOLO_DUNGEON_RANKING_PAGE] = 22;
			_sizes[ZC_SOLO_DUNGEON_STAGE_SCORE] = 34;
			_sizes[ZC_SOLO_DUNGEON_RANKING] = 0;
			_sizes[ZC_SOLO_DUNGEON_MY_RANKING] = 0;
			_sizes[ZC_CUSTOM_WHEEL_ZOOM] = 23;
			_sizes[ZC_MGAME_POSITION] = 0;
			_sizes[ZC_ITEM_LOCK_STATE] = 19;
			_sizes[ZC_SEND_COLONY_MARKET_FEE_PAYMENT_LIST] = 0;
			_sizes[CZ_REQ_COLONY_MARKET_FEE_PAYMENT] = 42;
			_sizes[CZ_REQ_GUILD_ASSET] = 22;
			_sizes[CZ_CHANGE_REPRESENTATION_CLASS] = 26;
			_sizes[ZC_PROPERTY_COMPARE_FOR_REP_CLASS] = 0;
			_sizes[ZC_UPDATE_REPRESENTATION_CLASS] = 22;
			_sizes[CZ_REQ_COMMANDER_INFO] = 24;
			_sizes[ZC_CUSTOM_COMMANDER_INFO] = 32;
			_sizes[ZC_TRUST_INFO] = 62;
			_sizes[ZC_GUILD_COOLDOWN_LIST] = 0;
			_sizes[CZ_REQUEST_CHARACTER_INDUN_INFO] = 22;
			_sizes[ZC_CLASS_RESET_POINT_INFO] = 18;
			_sizes[ZC_EQUIP_CARD_INFO] = 0;
			_sizes[ZC_EQUIP_GEM_INFO] = 0;
			_sizes[ZC_FADE_IN] = 14;
			_sizes[CZ_REQ_LEARN_ABILITY] = 0;
			_sizes[CZ_REQUEST_EVENT_USER_TYPE_INFO] = 22;
			_sizes[CZ_REQUEST_USED_MEDAL_TOTAL] = 22;
			_sizes[CZ_DPK_QUEST_DESTORY_SESSIONOBJ] = 286;
			_sizes[ZC_ZOMBIE_ALIVE] = 16;
			_sizes[CZ_ZOMBIE_ALIVE_ACK] = 22;
			_sizes[ZC_FRIENDLY_STATE] = 11;
			_sizes[ZC_CHANGE_SKIN_COLOR] = 18;
			_sizes[ZC_WEEKLY_BOSS_RANK_INFO] = 0;
			_sizes[ZC_WEEKLY_BOSS_RANK_MY_DAMAGE] = 22;
			_sizes[ZC_WEEKLY_BOSS_ACCUMULATED_DAMAGE] = 22;
			_sizes[ZC_WEEKLY_BOSS_ABSOLUTE_REWARD_LIST] = 0;
			_sizes[ZC_WEEKLY_BOSS_RECEIVED_ABSOLUTE_REWARD_LIST] = 0;
			_sizes[ZC_WEEKLY_BOSS_RANKING_REWARD_LIST] = 0;
			_sizes[ZC_WEEKLY_BOSS_RECEIVED_RANKING_REWARD] = 18;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_ABSOLUTE_REWARD_LIST] = 26;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_RANKING_REWARD_LIST] = 26;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_RECEIVE_RANKING_REWARD] = 26;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_RECEIVE_ABSOLUTE_REWARD] = 26;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_ACCEPT_ABSOLUTE_REWARD] = 34;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_ACCEPT_ABSOLUTE_REWARD_ALL] = 26;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_ACCEPT_RANKING_REWARD] = 30;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_RANKING_INFO_LIST] = 28;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_NOW_WEEK_NUM] = 22;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_START_TIME] = 26;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_END_TIME] = 26;
			_sizes[CZ_REQUEST_WEEKLY_BOSS_PATTERN_INFO] = 26;
			_sizes[ZC_WEEKLY_BOSS_NOW_WEEK_NUM] = 14;
			_sizes[ZC_WEEKLY_BOSS_START_TIME] = 26;
			_sizes[ZC_WEEKLY_BOSS_END_TIME] = 26;
			_sizes[ZC_WEEKLY_BOSS_PATTERN_INFO] = 0;
			_sizes[CZ_REQUEST_DPS_START] = 22;
			_sizes[ZC_REQUEST_DPS_START] = 26;
			_sizes[ZC_CONFUSE_STATE] = 15;
			_sizes[ZC_ADDONUI_MSG] = 0;
			_sizes[CZ_COLONY_REWARD_REQ] = 51;
			_sizes[ZC_COLONY_REWARD_DETAILLIST_UPDATE] = 22;
			_sizes[ZC_COLONY_SECONDLEAGUE_REWARD_START] = 38;
			_sizes[ZC_COLONY_SECONDLEAGUE_REWARD_END] = 38;
			_sizes[CZ_COLONY_TAXINQUIRELIST_REQ] = 22;
			_sizes[ZC_COLONY_TAXINQUIRELIST_REQ] = 0;
			_sizes[ZC_REBUILD_POPUP] = 16;
			_sizes[CZ_FORCE_SKILL_RANGE] = 54;
			_sizes[CZ_CANCEL_PAIR_ANIMATION] = 22;
			_sizes[ZC_SET_DAYLIGHT_INFO] = 0;
			_sizes[ZC_DAYLIGHT_SYNCHRONIZE_TIME] = 14;
			_sizes[ZC_DAYLIGHT_FIXED] = 35;
			_sizes[CZ_VARIABLE_RANGE_RESULT] = 38;
			_sizes[CZ_UDP_MOVE_INFO] = 65;
			_sizes[ZC_UDP_MOVE_INFO] = 80;
			_sizes[ZC_MAIN_SECTOR_INFO] = 0;
			_sizes[CZ_ACCEPT_FIELD_DUNGEON_REJOIN] = 22;


			foreach (var field in typeof(Op).GetFields(BindingFlags.Public | BindingFlags.Static))
				_names[(int)field.GetValue(null)] = field.Name;
		}

		public static int GetSize(int op)
		{
			if (!_sizes.TryGetValue(op, out var size))
				return -1;
			return size;
		}

		public static string GetName(int op)
		{
			if (!_names.TryGetValue(op, out var name))
				return "?";
			return name;
		}
	}
}
